// Code generated by Virtuous runtime; DO NOT EDIT.

/**
 * @typedef {Object} AuthOptions
 * @property {string} [auth]
 */

// Type definitions
/**
 * @typedef {Object} State
 * @property {number} id - Numeric state ID.
 * @property {string} code - Two-letter state code.
 * @property {string} name - Display name for the state.
 */
/**
 * @typedef {Object} StateResponse
 * @property {State} state
 * @property {string} [error]
 */
/**
 * @typedef {Object} StatesResponse
 * @property {State[]} data
 * @property {string} [error]
 */

/**
 * @param {string} [basepath="/"]
 * @returns {object}
 */
export function createClient(basepath = "/") {
	return {
		States: {
			/**
			 * Get state by code
			 *
			 * @param {Object} pathParams
			 * @param {AuthOptions} [options]
			 * @returns {Promise<StateResponse>}
			 */
			async getByCode(pathParams, options) {
				const headers = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/api/v1/lookup/states/{code}"
				if (!pathParams) {
					throw new Error("pathParams is required")
				}
				url = url.replace("{code}", encodeURIComponent(String(pathParams.code)))
				const response = await fetch(url, {
					method: "GET",
					headers,
				})
				const text = await response.text()
				let json = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new Error(response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					if (json && json.error) {
						throw new Error(json.error)
					}
					throw new Error(response.status + " " + response.statusText)
				}
				return json || {}
			},
			/**
			 * Get state by code (bearer token required)
			 *
			 * @param {Object} pathParams
			 * @param {AuthOptions} [options]
			 * @returns {Promise<StateResponse>}
			 */
			async getByCodeSecure(pathParams, options) {
				const headers = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/api/v1/secure/states/{code}"
				if (!pathParams) {
					throw new Error("pathParams is required")
				}
				url = url.replace("{code}", encodeURIComponent(String(pathParams.code)))
				const authValue = options && options.auth
				if (authValue) {
					headers["Authorization"] = "Bearer " + authValue
				}
				const response = await fetch(url, {
					method: "GET",
					headers,
				})
				const text = await response.text()
				let json = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new Error(response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					if (json && json.error) {
						throw new Error(json.error)
					}
					throw new Error(response.status + " " + response.statusText)
				}
				return json || {}
			},
			/**
			 * List all states
			 *
			 * @param {AuthOptions} [options]
			 * @returns {Promise<StatesResponse>}
			 */
			async getMany(options) {
				const headers = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/api/v1/lookup/states/"
				const response = await fetch(url, {
					method: "GET",
					headers,
				})
				const text = await response.text()
				let json = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new Error(response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					if (json && json.error) {
						throw new Error(json.error)
					}
					throw new Error(response.status + " " + response.statusText)
				}
				return json || {}
			},
		},
	}
}
