// Code generated by Virtuous runtime; DO NOT EDIT.

export type AuthOptions = {
	auth?: string
}

export interface State {
	id: number;
	code: string;
	name: string;
}

export interface StateResponse {
	state: State;
	error?: string;
}

export interface StatesResponse {
	data: State[];
	error?: string;
}

export function createClient(basepath: string = "/") {
	return {
		States: {
			async getByCode(pathParams: {code: string; }, options?: AuthOptions): Promise<StateResponse> {
				const headers: Record<string, string> = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/api/v1/lookup/states/{code}"
				if (!pathParams) {
					throw new Error("pathParams is required")
				}
				url = url.replace("{code}", encodeURIComponent(String(pathParams.code)))
				const response = await fetch(url, {
					method: "GET",
					headers,
				})
				const text = await response.text()
				let json: StateResponse | null = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new Error(response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					const errorBody = json as { error?: string } | null
					if (errorBody && errorBody.error) {
						throw new Error(errorBody.error)
					}
					throw new Error(response.status + " " + response.statusText)
				}
				return json as StateResponse
			},
			async getByCodeSecure(pathParams: {code: string; }, options?: AuthOptions): Promise<StateResponse> {
				const headers: Record<string, string> = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/api/v1/secure/states/{code}"
				if (!pathParams) {
					throw new Error("pathParams is required")
				}
				url = url.replace("{code}", encodeURIComponent(String(pathParams.code)))
				const authValue = options && options.auth
				if (authValue) {
					headers["Authorization"] = "Bearer " + authValue
				}
				const response = await fetch(url, {
					method: "GET",
					headers,
				})
				const text = await response.text()
				let json: StateResponse | null = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new Error(response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					const errorBody = json as { error?: string } | null
					if (errorBody && errorBody.error) {
						throw new Error(errorBody.error)
					}
					throw new Error(response.status + " " + response.statusText)
				}
				return json as StateResponse
			},
			async getMany(options?: AuthOptions): Promise<StatesResponse> {
				const headers: Record<string, string> = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/api/v1/lookup/states/"
				const response = await fetch(url, {
					method: "GET",
					headers,
				})
				const text = await response.text()
				let json: StatesResponse | null = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new Error(response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					const errorBody = json as { error?: string } | null
					if (errorBody && errorBody.error) {
						throw new Error(errorBody.error)
					}
					throw new Error(response.status + " " + response.statusText)
				}
				return json as StatesResponse
			},
		},
	}
}
