package clientgen

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestGeneratedLineIncludesVersionAndReadableTimestamp(t *testing.T) {
	generatedAt := time.Date(2026, 6, 6, 14, 32, 9, 0, time.FixedZone("Local", -5*60*60))
	line := GeneratedLine("//", generatedAt)

	if !strings.HasPrefix(line, "// Code generated by Virtuous "+VirtuousVersionLabel()+" on ") {
		t.Fatalf("generated line missing version prefix: %q", line)
	}
	if !strings.Contains(line, "2026-06-06 19:32:09 UTC") {
		t.Fatalf("generated line missing readable UTC timestamp: %q", line)
	}
	if !strings.HasSuffix(line, "; DO NOT EDIT.\n") {
		t.Fatalf("generated line missing do-not-edit suffix: %q", line)
	}
}

func TestFallbackVirtuousVersionMatchesVersionFile(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("..", "..", "VERSION"))
	if err != nil {
		t.Fatalf("read VERSION: %v", err)
	}
	want := strings.TrimSpace(string(data))
	if fallbackVirtuousVersion != want {
		t.Fatalf("fallback version = %q, want %q", fallbackVirtuousVersion, want)
	}
}

func TestBuildVersionRejectsLocalReplaceSentinel(t *testing.T) {
	for _, version := range []string{"", "(devel)", "0.0.0", "v0.0.0"} {
		if isBuildVersion(version) {
			t.Fatalf("isBuildVersion(%q) = true, want false", version)
		}
	}
	for _, version := range []string{"0.0.55", "v0.0.55"} {
		if !isBuildVersion(version) {
			t.Fatalf("isBuildVersion(%q) = false, want true", version)
		}
	}
}
