package clientgen

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"runtime/debug"
	"strings"
	"text/template"
	"time"
)

const (
	virtuousModulePath       = "github.com/swetjen/virtuous"
	fallbackVirtuousVersion  = "0.0.56"
	generatedTimestampFormat = "2006-01-02 15:04:05 UTC"
)

// RenderTemplate renders a client template into bytes.
func RenderTemplate(tmpl *template.Template, data any) ([]byte, error) {
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// HashBytes returns a stable SHA-256 hex digest for client artifacts.
func HashBytes(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}

// WriteArtifactHeader writes the generated artifact metadata that sits outside
// the stable generated body hash.
func WriteArtifactHeader(w io.Writer, commentPrefix, hashLabel, hash string) error {
	if _, err := fmt.Fprintf(w, "%s %s: %s\n", commentPrefix, hashLabel, hash); err != nil {
		return err
	}
	_, err := io.WriteString(w, GeneratedLine(commentPrefix, time.Now().UTC()))
	return err
}

// GeneratedLine returns a human-readable generated-file provenance line.
func GeneratedLine(commentPrefix string, generatedAt time.Time) string {
	return fmt.Sprintf(
		"%s Code generated by Virtuous %s on %s; DO NOT EDIT.\n",
		commentPrefix,
		VirtuousVersionLabel(),
		FormatGeneratedAt(generatedAt),
	)
}

// FormatGeneratedAt renders generation timestamps in a stable UTC format.
func FormatGeneratedAt(generatedAt time.Time) string {
	return generatedAt.UTC().Format(generatedTimestampFormat)
}

// VirtuousVersionLabel returns the version label displayed in generated assets.
func VirtuousVersionLabel() string {
	version := fallbackVirtuousVersion
	if info, ok := debug.ReadBuildInfo(); ok {
		if info.Path == virtuousModulePath && isBuildVersion(info.Main.Version) {
			version = info.Main.Version
		}
		for _, dep := range info.Deps {
			if dep.Path == virtuousModulePath {
				if dep.Replace != nil && isBuildVersion(dep.Replace.Version) {
					version = dep.Replace.Version
					break
				}
				if isBuildVersion(dep.Version) {
					version = dep.Version
					break
				}
			}
		}
	}
	if strings.HasPrefix(version, "v") {
		return version
	}
	return "v" + version
}

func isBuildVersion(version string) bool {
	return version != "" && version != "(devel)" && version != "0.0.0" && version != "v0.0.0"
}
