package rpc

import (
	"bytes"
	"io"
	"testing"

	"github.com/swetjen/virtuous/internal/clientgen"
)

func TestRPCLargeContractOutputIsDeterministic(t *testing.T) {
	router := NewRouter()
	router.SetTypeOverrides(map[string]TypeOverride{
		"PyContractDate": {
			JSType:        "string",
			PyType:        "date",
			OpenAPIType:   "string",
			OpenAPIFormat: "date",
		},
		"PyContractDecimal": {
			JSType:        "string",
			PyType:        "Decimal",
			OpenAPIType:   "string",
			OpenAPIFormat: "decimal",
		},
	})
	router.HandleRPC(pythonMegaContractHandler)
	router.HandleRPC(pgtypeHandler)

	assertRPCStableBytes(t, "openapi", func() ([]byte, error) { return router.OpenAPI() })
	assertRPCStableRender(t, "js", router.WriteClientJS)
	assertRPCStableRender(t, "ts", router.WriteClientTS)
	assertRPCStableRender(t, "py", router.WriteClientPY)
}

func assertRPCStableRender(t *testing.T, name string, render func(io.Writer) error) {
	t.Helper()
	assertRPCStableBytes(t, name, func() ([]byte, error) {
		var buf bytes.Buffer
		if err := render(&buf); err != nil {
			return nil, err
		}
		assertRPCGeneratedHeader(t, name, buf.Bytes())
		return buf.Bytes(), nil
	})
}

func assertRPCStableBytes(t *testing.T, name string, render func() ([]byte, error)) {
	t.Helper()
	first, err := render()
	if err != nil {
		t.Fatalf("%s first render: %v", name, err)
	}
	second, err := render()
	if err != nil {
		t.Fatalf("%s second render: %v", name, err)
	}
	if !bytes.Equal(first, second) {
		if bytes.Equal(stripRPCGeneratedTimestamp(first), stripRPCGeneratedTimestamp(second)) {
			return
		}
		t.Fatalf("%s output is not deterministic", name)
	}
}

func assertRPCGeneratedHeader(t *testing.T, name string, data []byte) {
	t.Helper()
	expected := []byte("Code generated by Virtuous " + clientgen.VirtuousVersionLabel() + " on ")
	if !bytes.Contains(data, expected) {
		t.Fatalf("%s output missing Virtuous version in generated header", name)
	}
	if !bytes.Contains(data, []byte(" UTC; DO NOT EDIT.")) {
		t.Fatalf("%s output missing generated timestamp in generated header", name)
	}
}

func stripRPCGeneratedTimestamp(data []byte) []byte {
	lines := bytes.Split(data, []byte("\n"))
	out := make([][]byte, 0, len(lines))
	for _, line := range lines {
		if bytes.Contains(line, []byte("Code generated by Virtuous ")) {
			continue
		}
		out = append(out, line)
	}
	return bytes.Join(out, []byte("\n"))
}
