package rpc

import (
	"encoding/json"
	"net/http"
)

// Framework error codes carried in ErrorBody.Code.
//
// These identify errors generated by the framework itself. Statuses returned
// by handlers (200/422/500) carry the handler's response type instead and
// never use these codes.
const (
	// ErrorCodeInvalidJSON marks a request body that could not be decoded as
	// JSON for the request type (HTTP 400).
	ErrorCodeInvalidJSON = "invalid_json"
	// ErrorCodeBodyTooLarge marks a request body over the configured size cap
	// (HTTP 413).
	ErrorCodeBodyTooLarge = "body_too_large"
	// ErrorCodeUnsupportedMediaType marks a request body sent without an
	// application/json Content-Type (HTTP 415).
	ErrorCodeUnsupportedMediaType = "unsupported_media_type"
	// ErrorCodeMethodNotAllowed marks a non-POST request to an RPC route
	// (HTTP 405).
	ErrorCodeMethodNotAllowed = "method_not_allowed"
	// ErrorCodeInternal marks a recovered handler panic (HTTP 500).
	ErrorCodeInternal = "internal"
)

// ErrorEnvelope is the wire shape of every framework-generated RPC error:
//
//	{"error": {"code": "<code>", "message": "<human message>"}}
//
// The framework writes it for HTTP 400 (invalid_json), 405
// (method_not_allowed), 413 (body_too_large), 415 (unsupported_media_type),
// and 500 (internal, recovered panic). Statuses returned by handlers
// (200/422/500) carry the handler's response type instead.
type ErrorEnvelope struct {
	Error ErrorBody `json:"error"`
}

// ErrorBody carries the machine-readable code and human-readable message of a
// framework-generated error.
type ErrorBody struct {
	// Code is a stable machine-readable identifier such as "invalid_json".
	Code string `json:"code"`
	// Message is a human-readable description safe to show to callers.
	Message string `json:"message"`
}

// writeErrorEnvelope writes a framework-generated error response using the
// canonical envelope shape.
func writeErrorEnvelope(w http.ResponseWriter, status int, code, message string) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	// Headers are already written; do not attempt another status line on
	// encode/write failure.
	_ = json.NewEncoder(w).Encode(ErrorEnvelope{Error: ErrorBody{Code: code, Message: message}})
}
