// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: states.sql

package db

import (
	"context"
)

const createState = `-- name: CreateState :one
INSERT INTO states (code, name)
VALUES (?, ?)
RETURNING id, code, name
`

type CreateStateParams struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

func (q *Queries) CreateState(ctx context.Context, arg CreateStateParams) (State, error) {
	row := q.db.QueryRowContext(ctx, createState, arg.Code, arg.Name)
	var i State
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const getStateByCode = `-- name: GetStateByCode :one
SELECT id, code, name
FROM states
WHERE lower(code) = lower(?)
`

func (q *Queries) GetStateByCode(ctx context.Context, lower string) (State, error) {
	row := q.db.QueryRowContext(ctx, getStateByCode, lower)
	var i State
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const listStates = `-- name: ListStates :many
SELECT id, code, name
FROM states
ORDER BY name
`

func (q *Queries) ListStates(ctx context.Context) ([]State, error) {
	rows, err := q.db.QueryContext(ctx, listStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []State
	for rows.Next() {
		var i State
		if err := rows.Scan(&i.ID, &i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
