# Virtuous client hash: ff18156dc5f6549b56c86866f4e7219d2d4fd51be2d3861ab08eec3f13101194
# Code generated by Virtuous runtime; DO NOT EDIT.

"""Runtime-generated Python client for Virtuous RPC routes."""

from dataclasses import dataclass, fields, is_dataclass
import http
import json
import types
from typing import Any, Union, get_args, get_origin, get_type_hints
from urllib import error, parse, request

# Type definitions
@dataclass
class AdminUser:
    # User ID.
    id: int
    # Login email address.
    email: str
    # Display name.
    name: str
    # Authorization role.
    role: str
    # Whether the account is disabled.
    disabled: bool

@dataclass
class AdminUserByIDRequest:
    id: str

@dataclass
class AdminUserDisableRequest:
    id: str

@dataclass
class AdminUserResponse:
    user: "AdminUser"
    temporary_password: str | None = None
    error: str | None = None

@dataclass
class AdminUsersResponse:
    data: list["AdminUser"]
    error: str | None = None

@dataclass
class ConfirmRequest:
    code: str

@dataclass
class ConfirmResponse:
    user: "UserInDb"
    error: str | None = None

@dataclass
class CreateAdminUserRequest:
    email: str
    name: str
    role: str
    password: str | None = None

@dataclass
class CreateStateRequest:
    code: str
    name: str

@dataclass
class LoginCredsRequest:
    email: str
    password: str

@dataclass
class LoginResponse:
    user: "UserInDb"
    token: str | None = None
    error: str | None = None

@dataclass
class MeResponse:
    user: "UserInDb"
    error: str | None = None

@dataclass
class RegisterRequest:
    email: str
    name: str
    password: str

@dataclass
class RegisterResponse:
    user: "UserInDb"
    confirmation_code: str | None = None
    error: str | None = None

@dataclass
class State:
    # State ID.
    id: int
    # Two-letter state code.
    code: str
    # Display name.
    name: str

@dataclass
class StateByCodeRequest:
    code: str

@dataclass
class StateResponse:
    state: "State"
    error: str | None = None

@dataclass
class StatesResponse:
    data: list["State"]
    error: str | None = None

@dataclass
class UserInDb:
    # User ID.
    id: int
    # Login email address.
    email: str
    # Display name.
    name: str
    # Authorization role.
    role: str
    # Whether the user is an admin.
    is_superuser: bool
    # Whether the account is disabled.
    disabled: bool

class RPCError(RuntimeError):
    def __init__(self, status: int, body: Any, message: str):
        super().__init__(message)
        self.status = status
        self.body = body
class _adminService:
    def __init__(self, basepath: str):
        self._basepath = basepath
    def UserByID(self, body:"AdminUserByIDRequest", adminSessionAuth: str | None = None) ->"AdminUserResponse":
        headers = {
            "Accept": "application/json",
            "Content-Type": "application/json",
        }
        url = self._basepath + "/rpc/admin/user-by-id"
        if adminSessionAuth is not None:
            auth_value = adminSessionAuth
            auth_value = "Bearer " + adminSessionAuth
            headers["Authorization"] = auth_value
        data = None
        data = json.dumps(_encode_value(body)).encode("utf-8")
        req = request.Request(url, data=data, method="POST", headers=headers)
        status = 0
        text = ""
        try:
            with request.urlopen(req) as resp:
                status = resp.getcode()
                text = resp.read().decode("utf-8")
        except error.HTTPError as err:
            status = err.code
            text = err.read().decode("utf-8")
        body = None
        if text:
            try:
                body = json.loads(text)
            except json.JSONDecodeError as err:
                raise RPCError(status, None, f"{status} {_status_text(status)}") from err
        if status >= 400:
            err_body = _decode_value("AdminUserResponse", body)
            raise RPCError(status, err_body, f"{status} {_status_text(status)}")
        return _decode_value("AdminUserResponse", body)
    def UserCreate(self, body:"CreateAdminUserRequest", adminSessionAuth: str | None = None) ->"AdminUserResponse":
        headers = {
            "Accept": "application/json",
            "Content-Type": "application/json",
        }
        url = self._basepath + "/rpc/admin/user-create"
        if adminSessionAuth is not None:
            auth_value = adminSessionAuth
            auth_value = "Bearer " + adminSessionAuth
            headers["Authorization"] = auth_value
        data = None
        data = json.dumps(_encode_value(body)).encode("utf-8")
        req = request.Request(url, data=data, method="POST", headers=headers)
        status = 0
        text = ""
        try:
            with request.urlopen(req) as resp:
                status = resp.getcode()
                text = resp.read().decode("utf-8")
        except error.HTTPError as err:
            status = err.code
            text = err.read().decode("utf-8")
        body = None
        if text:
            try:
                body = json.loads(text)
            except json.JSONDecodeError as err:
                raise RPCError(status, None, f"{status} {_status_text(status)}") from err
        if status >= 400:
            err_body = _decode_value("AdminUserResponse", body)
            raise RPCError(status, err_body, f"{status} {_status_text(status)}")
        return _decode_value("AdminUserResponse", body)
    def UserDisable(self, body:"AdminUserDisableRequest", adminSessionAuth: str | None = None) ->"AdminUserResponse":
        headers = {
            "Accept": "application/json",
            "Content-Type": "application/json",
        }
        url = self._basepath + "/rpc/admin/user-disable"
        if adminSessionAuth is not None:
            auth_value = adminSessionAuth
            auth_value = "Bearer " + adminSessionAuth
            headers["Authorization"] = auth_value
        data = None
        data = json.dumps(_encode_value(body)).encode("utf-8")
        req = request.Request(url, data=data, method="POST", headers=headers)
        status = 0
        text = ""
        try:
            with request.urlopen(req) as resp:
                status = resp.getcode()
                text = resp.read().decode("utf-8")
        except error.HTTPError as err:
            status = err.code
            text = err.read().decode("utf-8")
        body = None
        if text:
            try:
                body = json.loads(text)
            except json.JSONDecodeError as err:
                raise RPCError(status, None, f"{status} {_status_text(status)}") from err
        if status >= 400:
            err_body = _decode_value("AdminUserResponse", body)
            raise RPCError(status, err_body, f"{status} {_status_text(status)}")
        return _decode_value("AdminUserResponse", body)
    def UsersGetMany(self, adminSessionAuth: str | None = None) ->"AdminUsersResponse":
        headers = {
            "Accept": "application/json",
            "Content-Type": "application/json",
        }
        url = self._basepath + "/rpc/admin/users-get-many"
        if adminSessionAuth is not None:
            auth_value = adminSessionAuth
            auth_value = "Bearer " + adminSessionAuth
            headers["Authorization"] = auth_value
        data = None
        req = request.Request(url, data=data, method="POST", headers=headers)
        status = 0
        text = ""
        try:
            with request.urlopen(req) as resp:
                status = resp.getcode()
                text = resp.read().decode("utf-8")
        except error.HTTPError as err:
            status = err.code
            text = err.read().decode("utf-8")
        body = None
        if text:
            try:
                body = json.loads(text)
            except json.JSONDecodeError as err:
                raise RPCError(status, None, f"{status} {_status_text(status)}") from err
        if status >= 400:
            err_body = _decode_value("AdminUsersResponse", body)
            raise RPCError(status, err_body, f"{status} {_status_text(status)}")
        return _decode_value("AdminUsersResponse", body)
class _statesService:
    def __init__(self, basepath: str):
        self._basepath = basepath
    def StateByCode(self, body:"StateByCodeRequest") ->"StateResponse":
        headers = {
            "Accept": "application/json",
            "Content-Type": "application/json",
        }
        url = self._basepath + "/rpc/states/state-by-code"
        data = None
        data = json.dumps(_encode_value(body)).encode("utf-8")
        req = request.Request(url, data=data, method="POST", headers=headers)
        status = 0
        text = ""
        try:
            with request.urlopen(req) as resp:
                status = resp.getcode()
                text = resp.read().decode("utf-8")
        except error.HTTPError as err:
            status = err.code
            text = err.read().decode("utf-8")
        body = None
        if text:
            try:
                body = json.loads(text)
            except json.JSONDecodeError as err:
                raise RPCError(status, None, f"{status} {_status_text(status)}") from err
        if status >= 400:
            err_body = _decode_value("StateResponse", body)
            raise RPCError(status, err_body, f"{status} {_status_text(status)}")
        return _decode_value("StateResponse", body)
    def StateCreate(self, body:"CreateStateRequest") ->"StateResponse":
        headers = {
            "Accept": "application/json",
            "Content-Type": "application/json",
        }
        url = self._basepath + "/rpc/states/state-create"
        data = None
        data = json.dumps(_encode_value(body)).encode("utf-8")
        req = request.Request(url, data=data, method="POST", headers=headers)
        status = 0
        text = ""
        try:
            with request.urlopen(req) as resp:
                status = resp.getcode()
                text = resp.read().decode("utf-8")
        except error.HTTPError as err:
            status = err.code
            text = err.read().decode("utf-8")
        body = None
        if text:
            try:
                body = json.loads(text)
            except json.JSONDecodeError as err:
                raise RPCError(status, None, f"{status} {_status_text(status)}") from err
        if status >= 400:
            err_body = _decode_value("StateResponse", body)
            raise RPCError(status, err_body, f"{status} {_status_text(status)}")
        return _decode_value("StateResponse", body)
    def StatesGetMany(self) ->"StatesResponse":
        headers = {
            "Accept": "application/json",
            "Content-Type": "application/json",
        }
        url = self._basepath + "/rpc/states/states-get-many"
        data = None
        req = request.Request(url, data=data, method="POST", headers=headers)
        status = 0
        text = ""
        try:
            with request.urlopen(req) as resp:
                status = resp.getcode()
                text = resp.read().decode("utf-8")
        except error.HTTPError as err:
            status = err.code
            text = err.read().decode("utf-8")
        body = None
        if text:
            try:
                body = json.loads(text)
            except json.JSONDecodeError as err:
                raise RPCError(status, None, f"{status} {_status_text(status)}") from err
        if status >= 400:
            err_body = _decode_value("StatesResponse", body)
            raise RPCError(status, err_body, f"{status} {_status_text(status)}")
        return _decode_value("StatesResponse", body)
class _usersService:
    def __init__(self, basepath: str):
        self._basepath = basepath
    def UserConfirm(self, body:"ConfirmRequest") ->"ConfirmResponse":
        headers = {
            "Accept": "application/json",
            "Content-Type": "application/json",
        }
        url = self._basepath + "/rpc/users/user-confirm"
        data = None
        data = json.dumps(_encode_value(body)).encode("utf-8")
        req = request.Request(url, data=data, method="POST", headers=headers)
        status = 0
        text = ""
        try:
            with request.urlopen(req) as resp:
                status = resp.getcode()
                text = resp.read().decode("utf-8")
        except error.HTTPError as err:
            status = err.code
            text = err.read().decode("utf-8")
        body = None
        if text:
            try:
                body = json.loads(text)
            except json.JSONDecodeError as err:
                raise RPCError(status, None, f"{status} {_status_text(status)}") from err
        if status >= 400:
            err_body = _decode_value("ConfirmResponse", body)
            raise RPCError(status, err_body, f"{status} {_status_text(status)}")
        return _decode_value("ConfirmResponse", body)
    def UserLogin(self, body:"LoginCredsRequest") ->"LoginResponse":
        headers = {
            "Accept": "application/json",
            "Content-Type": "application/json",
        }
        url = self._basepath + "/rpc/users/user-login"
        data = None
        data = json.dumps(_encode_value(body)).encode("utf-8")
        req = request.Request(url, data=data, method="POST", headers=headers)
        status = 0
        text = ""
        try:
            with request.urlopen(req) as resp:
                status = resp.getcode()
                text = resp.read().decode("utf-8")
        except error.HTTPError as err:
            status = err.code
            text = err.read().decode("utf-8")
        body = None
        if text:
            try:
                body = json.loads(text)
            except json.JSONDecodeError as err:
                raise RPCError(status, None, f"{status} {_status_text(status)}") from err
        if status >= 400:
            err_body = _decode_value("LoginResponse", body)
            raise RPCError(status, err_body, f"{status} {_status_text(status)}")
        return _decode_value("LoginResponse", body)
    def UserMe(self, userSessionAuth: str | None = None) ->"MeResponse":
        headers = {
            "Accept": "application/json",
            "Content-Type": "application/json",
        }
        url = self._basepath + "/rpc/users/user-me"
        if userSessionAuth is not None:
            auth_value = userSessionAuth
            auth_value = "Bearer " + userSessionAuth
            headers["Authorization"] = auth_value
        data = None
        req = request.Request(url, data=data, method="POST", headers=headers)
        status = 0
        text = ""
        try:
            with request.urlopen(req) as resp:
                status = resp.getcode()
                text = resp.read().decode("utf-8")
        except error.HTTPError as err:
            status = err.code
            text = err.read().decode("utf-8")
        body = None
        if text:
            try:
                body = json.loads(text)
            except json.JSONDecodeError as err:
                raise RPCError(status, None, f"{status} {_status_text(status)}") from err
        if status >= 400:
            err_body = _decode_value("MeResponse", body)
            raise RPCError(status, err_body, f"{status} {_status_text(status)}")
        return _decode_value("MeResponse", body)
    def UserRegister(self, body:"RegisterRequest") ->"RegisterResponse":
        headers = {
            "Accept": "application/json",
            "Content-Type": "application/json",
        }
        url = self._basepath + "/rpc/users/user-register"
        data = None
        data = json.dumps(_encode_value(body)).encode("utf-8")
        req = request.Request(url, data=data, method="POST", headers=headers)
        status = 0
        text = ""
        try:
            with request.urlopen(req) as resp:
                status = resp.getcode()
                text = resp.read().decode("utf-8")
        except error.HTTPError as err:
            status = err.code
            text = err.read().decode("utf-8")
        body = None
        if text:
            try:
                body = json.loads(text)
            except json.JSONDecodeError as err:
                raise RPCError(status, None, f"{status} {_status_text(status)}") from err
        if status >= 400:
            err_body = _decode_value("RegisterResponse", body)
            raise RPCError(status, err_body, f"{status} {_status_text(status)}")
        return _decode_value("RegisterResponse", body)

class Client:
    def __init__(self, basepath: str = "/"):
        self._basepath = basepath
        self.admin = _adminService(basepath)
        self.states = _statesService(basepath)
        self.users = _usersService(basepath)


def create_client(basepath: str = "/") -> Client:
    return Client(basepath)


def _status_text(code: int) -> str:
    try:
        return http.HTTPStatus(code).phrase
    except ValueError:
        return "HTTP error"


def _decode_value(tp: Any, value: Any) -> Any:
    if value is None:
        return None
    origin = get_origin(tp)
    if origin is None:
        if is_dataclass(tp):
            return _decode_dataclass(tp, value)
        return value
    if origin is list:
        args = get_args(tp)
        elem_type = args[0] if args else Any
        return [_decode_value(elem_type, item) for item in value]
    if origin is dict:
        args = get_args(tp)
        value_type = args[1] if len(args) > 1 else Any
        return {key: _decode_value(value_type, item) for key, item in value.items()}
    if origin in (Union, types.UnionType):
        args = [arg for arg in get_args(tp) if arg is not type(None)]
        if len(args) == 1:
            return _decode_value(args[0], value)
        return value
    return value


def _decode_dataclass(cls: type[Any], data: Any) -> Any:
    if data is None:
        return None
    if not isinstance(data, dict):
        return data
    type_hints = get_type_hints(cls)
    kwargs: dict[str, Any] = {}
    for field in fields(cls):
        if field.name in data:
            field_type = type_hints.get(field.name, Any)
            kwargs[field.name] = _decode_value(field_type, data[field.name])
    return cls(**kwargs)


def _encode_value(value: Any) -> Any:
    if value is None:
        return None
    if is_dataclass(value):
        return {field.name: _encode_value(getattr(value, field.name)) for field in fields(value)}
    if isinstance(value, list):
        return [_encode_value(item) for item in value]
    if isinstance(value, dict):
        return {key: _encode_value(item) for key, item in value.items()}
    return value


def _append_query(url: str, key: str, value: str) -> str:
    parts = parse.urlsplit(url)
    query = parse.parse_qsl(parts.query, keep_blank_values=True)
    query.append((key, value))
    new_query = parse.urlencode(query)
    return parse.urlunsplit((parts.scheme, parts.netloc, parts.path, new_query, parts.fragment))
