// Virtuous client hash: 4076fb099aa183df87739c300468873a194753fad8ff4d1d428370f9652e3a91
// Code generated by Virtuous runtime; DO NOT EDIT.

export type AuthOptions = {
	auth?: string
}

export class RPCError<E = unknown> extends Error {
	status: number
	body: E | null
	constructor(status: number, body: E | null, message: string) {
		super(message)
		this.status = status
		this.body = body
	}
}


export interface AdminUser {
	id: number;
	email: string;
	name: string;
	role: string;
	disabled: boolean;
}

export interface AdminUserByIDRequest {
	id: string;
}

export interface AdminUserDisableRequest {
	id: string;
}

export interface AdminUserResponse {
	user: AdminUser;
	temporary_password?: string;
	error?: string;
}

export interface AdminUsersResponse {
	data: AdminUser[];
	error?: string;
}

export interface ConfirmRequest {
	code: string;
}

export interface ConfirmResponse {
	user: UserInDb;
	error?: string;
}

export interface CreateAdminUserRequest {
	email: string;
	name: string;
	role: string;
	password?: string;
}

export interface CreateStateRequest {
	code: string;
	name: string;
}

export interface LoginCredsRequest {
	email: string;
	password: string;
}

export interface LoginResponse {
	user: UserInDb;
	token?: string;
	error?: string;
}

export interface MeResponse {
	user: UserInDb;
	error?: string;
}

export interface RegisterRequest {
	email: string;
	name: string;
	password: string;
}

export interface RegisterResponse {
	user: UserInDb;
	confirmation_code?: string;
	error?: string;
}

export interface State {
	id: number;
	code: string;
	name: string;
}

export interface StateByCodeRequest {
	code: string;
}

export interface StateResponse {
	state: State;
	error?: string;
}

export interface StatesResponse {
	data: State[];
	error?: string;
}

export interface UserInDb {
	id: number;
	email: string;
	name: string;
	role: string;
	is_superuser: boolean;
	disabled: boolean;
}

export function createClient(basepath: string = "/") {
	return {
		admin: {
			async UserByID(request: AdminUserByIDRequest, options?: AuthOptions): Promise<AdminUserResponse> {
				const headers: Record<string, string> = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/rpc/admin/user-by-id"
				const authValue = options && options.auth
				if (authValue) {
					headers["Authorization"] = "Bearer " + authValue
				}
				const response = await fetch(url, {
					method: "POST",
					headers,
					body: JSON.stringify(request),
				})
				const text = await response.text()
				let json: AdminUserResponse | null = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new RPCError<AdminUserResponse>(response.status, null, response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					throw new RPCError<AdminUserResponse>(response.status, json as AdminUserResponse, response.status + " " + response.statusText)
				}
				return json as AdminUserResponse
			},
			async UserCreate(request: CreateAdminUserRequest, options?: AuthOptions): Promise<AdminUserResponse> {
				const headers: Record<string, string> = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/rpc/admin/user-create"
				const authValue = options && options.auth
				if (authValue) {
					headers["Authorization"] = "Bearer " + authValue
				}
				const response = await fetch(url, {
					method: "POST",
					headers,
					body: JSON.stringify(request),
				})
				const text = await response.text()
				let json: AdminUserResponse | null = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new RPCError<AdminUserResponse>(response.status, null, response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					throw new RPCError<AdminUserResponse>(response.status, json as AdminUserResponse, response.status + " " + response.statusText)
				}
				return json as AdminUserResponse
			},
			async UserDisable(request: AdminUserDisableRequest, options?: AuthOptions): Promise<AdminUserResponse> {
				const headers: Record<string, string> = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/rpc/admin/user-disable"
				const authValue = options && options.auth
				if (authValue) {
					headers["Authorization"] = "Bearer " + authValue
				}
				const response = await fetch(url, {
					method: "POST",
					headers,
					body: JSON.stringify(request),
				})
				const text = await response.text()
				let json: AdminUserResponse | null = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new RPCError<AdminUserResponse>(response.status, null, response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					throw new RPCError<AdminUserResponse>(response.status, json as AdminUserResponse, response.status + " " + response.statusText)
				}
				return json as AdminUserResponse
			},
			async UsersGetMany(options?: AuthOptions): Promise<AdminUsersResponse> {
				const headers: Record<string, string> = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/rpc/admin/users-get-many"
				const authValue = options && options.auth
				if (authValue) {
					headers["Authorization"] = "Bearer " + authValue
				}
				const response = await fetch(url, {
					method: "POST",
					headers,
				})
				const text = await response.text()
				let json: AdminUsersResponse | null = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new RPCError<AdminUsersResponse>(response.status, null, response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					throw new RPCError<AdminUsersResponse>(response.status, json as AdminUsersResponse, response.status + " " + response.statusText)
				}
				return json as AdminUsersResponse
			},
		},
		states: {
			async StateByCode(request: StateByCodeRequest, options?: AuthOptions): Promise<StateResponse> {
				const headers: Record<string, string> = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/rpc/states/state-by-code"
				const response = await fetch(url, {
					method: "POST",
					headers,
					body: JSON.stringify(request),
				})
				const text = await response.text()
				let json: StateResponse | null = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new RPCError<StateResponse>(response.status, null, response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					throw new RPCError<StateResponse>(response.status, json as StateResponse, response.status + " " + response.statusText)
				}
				return json as StateResponse
			},
			async StateCreate(request: CreateStateRequest, options?: AuthOptions): Promise<StateResponse> {
				const headers: Record<string, string> = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/rpc/states/state-create"
				const response = await fetch(url, {
					method: "POST",
					headers,
					body: JSON.stringify(request),
				})
				const text = await response.text()
				let json: StateResponse | null = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new RPCError<StateResponse>(response.status, null, response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					throw new RPCError<StateResponse>(response.status, json as StateResponse, response.status + " " + response.statusText)
				}
				return json as StateResponse
			},
			async StatesGetMany(options?: AuthOptions): Promise<StatesResponse> {
				const headers: Record<string, string> = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/rpc/states/states-get-many"
				const response = await fetch(url, {
					method: "POST",
					headers,
				})
				const text = await response.text()
				let json: StatesResponse | null = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new RPCError<StatesResponse>(response.status, null, response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					throw new RPCError<StatesResponse>(response.status, json as StatesResponse, response.status + " " + response.statusText)
				}
				return json as StatesResponse
			},
		},
		users: {
			async UserConfirm(request: ConfirmRequest, options?: AuthOptions): Promise<ConfirmResponse> {
				const headers: Record<string, string> = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/rpc/users/user-confirm"
				const response = await fetch(url, {
					method: "POST",
					headers,
					body: JSON.stringify(request),
				})
				const text = await response.text()
				let json: ConfirmResponse | null = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new RPCError<ConfirmResponse>(response.status, null, response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					throw new RPCError<ConfirmResponse>(response.status, json as ConfirmResponse, response.status + " " + response.statusText)
				}
				return json as ConfirmResponse
			},
			async UserLogin(request: LoginCredsRequest, options?: AuthOptions): Promise<LoginResponse> {
				const headers: Record<string, string> = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/rpc/users/user-login"
				const response = await fetch(url, {
					method: "POST",
					headers,
					body: JSON.stringify(request),
				})
				const text = await response.text()
				let json: LoginResponse | null = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new RPCError<LoginResponse>(response.status, null, response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					throw new RPCError<LoginResponse>(response.status, json as LoginResponse, response.status + " " + response.statusText)
				}
				return json as LoginResponse
			},
			async UserMe(options?: AuthOptions): Promise<MeResponse> {
				const headers: Record<string, string> = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/rpc/users/user-me"
				const authValue = options && options.auth
				if (authValue) {
					headers["Authorization"] = "Bearer " + authValue
				}
				const response = await fetch(url, {
					method: "POST",
					headers,
				})
				const text = await response.text()
				let json: MeResponse | null = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new RPCError<MeResponse>(response.status, null, response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					throw new RPCError<MeResponse>(response.status, json as MeResponse, response.status + " " + response.statusText)
				}
				return json as MeResponse
			},
			async UserRegister(request: RegisterRequest, options?: AuthOptions): Promise<RegisterResponse> {
				const headers: Record<string, string> = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/rpc/users/user-register"
				const response = await fetch(url, {
					method: "POST",
					headers,
					body: JSON.stringify(request),
				})
				const text = await response.text()
				let json: RegisterResponse | null = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new RPCError<RegisterResponse>(response.status, null, response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					throw new RPCError<RegisterResponse>(response.status, json as RegisterResponse, response.status + " " + response.statusText)
				}
				return json as RegisterResponse
			},
		},
	}
}
