// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: states.sql

package db

import (
	"context"
)

const createState = `-- name: CreateState :one
INSERT INTO states (code, name)
VALUES ($1, $2)
RETURNING id, code, name
`

func (q *Queries) CreateState(ctx context.Context, code string, name string) (State, error) {
	row := q.db.QueryRow(ctx, createState, code, name)
	var i State
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const getStateByCode = `-- name: GetStateByCode :one
SELECT id, code, name
FROM states
WHERE code = $1
`

func (q *Queries) GetStateByCode(ctx context.Context, code string) (State, error) {
	row := q.db.QueryRow(ctx, getStateByCode, code)
	var i State
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const listStates = `-- name: ListStates :many
SELECT id, code, name
FROM states
ORDER BY name
`

func (q *Queries) ListStates(ctx context.Context) ([]State, error) {
	rows, err := q.db.Query(ctx, listStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []State{}
	for rows.Next() {
		var i State
		if err := rows.Scan(&i.ID, &i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
