package httpapi

import (
	"bytes"
	"io"
	"testing"

	"github.com/swetjen/virtuous/internal/clientgen"
)

func TestHTTPAPILargeContractOutputIsDeterministic(t *testing.T) {
	router := NewRouter()
	router.SetTypeOverrides(httpPythonContractTypeOverrides())
	router.Describe("POST /contracts/python/mega", HTTPPythonMegaRequest{}, HTTPPythonMegaResponse{}, HandlerMeta{
		Service:     "Contracts",
		Method:      "Mega",
		OperationID: "python_mega",
	})
	router.Describe("PUT /contracts/{account_id}/mixed", HTTPPythonMixedRequest{}, HTTPPythonOptionalResponse{}, HandlerMeta{
		Service:     "Contracts",
		Method:      "Mixed",
		OperationID: "python_mixed",
	})
	router.Describe("POST /db/pgtype", httpPgtypeRequest{}, httpPgtypeResponse{}, HandlerMeta{
		Service:     "DB",
		Method:      "RoundTrip",
		OperationID: "pgtype_round_trip",
	})

	assertStableBytes(t, "openapi", func() ([]byte, error) { return router.OpenAPI() })
	assertStableRender(t, "js", router.WriteClientJS)
	assertStableRender(t, "ts", router.WriteClientTS)
	assertStableRender(t, "py", router.WriteClientPY)
	assertStableRender(t, "react-query-ts", router.WriteReactQueryTS)
}

func assertStableRender(t *testing.T, name string, render func(io.Writer) error) {
	t.Helper()
	assertStableBytes(t, name, func() ([]byte, error) {
		var buf bytes.Buffer
		if err := render(&buf); err != nil {
			return nil, err
		}
		assertGeneratedHeader(t, name, buf.Bytes())
		return buf.Bytes(), nil
	})
}

func assertStableBytes(t *testing.T, name string, render func() ([]byte, error)) {
	t.Helper()
	first, err := render()
	if err != nil {
		t.Fatalf("%s first render: %v", name, err)
	}
	second, err := render()
	if err != nil {
		t.Fatalf("%s second render: %v", name, err)
	}
	if !bytes.Equal(first, second) {
		if bytes.Equal(stripGeneratedTimestamp(first), stripGeneratedTimestamp(second)) {
			return
		}
		t.Fatalf("%s output is not deterministic", name)
	}
}

func assertGeneratedHeader(t *testing.T, name string, data []byte) {
	t.Helper()
	expected := []byte("Code generated by Virtuous " + clientgen.VirtuousVersionLabel() + " on ")
	if !bytes.Contains(data, expected) {
		t.Fatalf("%s output missing Virtuous version in generated header", name)
	}
	if !bytes.Contains(data, []byte(" UTC; DO NOT EDIT.")) {
		t.Fatalf("%s output missing generated timestamp in generated header", name)
	}
}

func stripGeneratedTimestamp(data []byte) []byte {
	lines := bytes.Split(data, []byte("\n"))
	out := make([][]byte, 0, len(lines))
	for _, line := range lines {
		if bytes.Contains(line, []byte("Code generated by Virtuous ")) {
			continue
		}
		out = append(out, line)
	}
	return bytes.Join(out, []byte("\n"))
}
