package httpapi

import (
	"github.com/swetjen/virtuous/internal/clientgen"
	"io"
	"net/http"
	"os"
	"strings"
	"text/template"
	"unicode"
)

var clientPyTemplate = template.Must(template.New("virtuous-py").Parse(`# Code generated by Virtuous; DO NOT EDIT.

"""Generated Python client for Virtuous routes."""

from dataclasses import dataclass, field, fields, is_dataclass
from datetime import datetime
import http
import json
import types
import uuid
from typing import Any, Optional, Union, get_args, get_origin, get_type_hints
from urllib import error, parse, request

# Type definitions
{{- range $i, $object := .Objects }}
{{- if gt $i 0 }}{{ "\n" }}{{ end }}
@dataclass(kw_only=True)
class {{ $object.Name }}:
{{- if not $object.Fields }}
    pass
{{- else }}
{{- range $field := $object.Fields }}
{{- if $field.Doc }}
    # {{ $field.Doc }}
{{- end }}
    {{ $field.Declaration }}
{{- end }}
{{- end }}

{{- end }}

{{- range $service := .Services }}
class {{ $service.ClassName }}:
    def __init__(self, base_url: str{{- if $service.AuthParams }}, *{{- range $auth := $service.AuthParams }}, {{ $auth.ParamName }}: Optional[str] = None{{- end }}{{- end }}):
        self._base_url = base_url
{{- range $auth := $service.AuthParams }}
        self.{{ $auth.DefaultAttr }} = {{ $auth.ParamName }}
{{- end }}

{{- range $method := $service.Methods }}
    def {{ $method.Name }}(self{{ $method.SignatureParams }}) -> {{ $method.ReturnType }}:
        headers = {
            "Accept": "{{ $method.AcceptType }}",
{{- if $method.HasBody }}
{{- if ne $method.BodyMode "multipart" }}
            "Content-Type": "{{ $method.RequestMedia }}",
{{- end }}
{{- end }}
        }
        url = self._base_url + "{{ $method.Path }}"
{{- if $method.PathParams }}
{{- range $param := $method.PathParams }}
        url = url.replace("{{ printf "{%s}" $param.Name }}", parse.quote(str({{ $param.VarName }})))
{{- end }}
{{- end }}
{{- if $method.HasQuery }}
{{- range $param := $method.QueryParams }}
        url = _append_query_param(url, "{{ $param.WireName }}", {{ $param.VarName }}, {{ if $param.Optional }}True{{ else }}False{{ end }})
{{- end }}
{{- end }}
{{- if $method.HasAuth }}
        auth_applied = False
{{- range $req := $method.AuthReqs }}
        if not auth_applied:
{{- if eq (len $req.Guards) 1 }}
{{- range $guard := $req.Guards }}
            auth_value = {{ $guard.ParamName }} if {{ $guard.ParamName }} is not None else self.{{ $guard.DefaultAttr }}
            if auth_value is not None:
                url = _apply_auth(url, headers, "{{ $guard.Spec.In }}", "{{ $guard.Spec.Param }}", "{{ $guard.Spec.Prefix }}", auth_value)
                auth_applied = True
{{- end }}
{{- else }}
{{- range $guard := $req.Guards }}
            {{ $guard.ValueName }} = {{ $guard.ParamName }} if {{ $guard.ParamName }} is not None else self.{{ $guard.DefaultAttr }}
{{- end }}
            if {{ range $i, $guard := $req.Guards }}{{ if gt $i 0 }} and {{ end }}{{ $guard.ValueName }} is not None{{ end }}:
{{- range $guard := $req.Guards }}
                url = _apply_auth(url, headers, "{{ $guard.Spec.In }}", "{{ $guard.Spec.Param }}", "{{ $guard.Spec.Prefix }}", {{ $guard.ValueName }})
{{- end }}
                auth_applied = True
{{- end }}
{{- end }}
        if not auth_applied:
            raise RuntimeError("auth not configured: {{ $method.AuthError }}")
{{- end }}
        data = None
{{- if $method.HasBody }}
        if body is not None:
            data, content_type = _encode_body(body, "{{ $method.BodyMode }}", [
{{- range $field := $method.BodyFields }}
                ("{{ $field.WireName }}", "{{ $field.ValueName }}", {{ if $field.IsFile }}True{{ else }}False{{ end }}),
{{- end }}
            ])
            if content_type:
                headers["Content-Type"] = content_type
{{- end }}
        return _request("{{ $method.HTTPMethod }}", url, headers, data, "{{ $method.ResponseMode }}", {{ if $method.ResponseDecodeType }}{{ $method.ResponseDecodeType }}{{ else }}None{{ end }})

{{- end }}
{{- end }}

class _VirtuousClient:
    def __init__(self, base_url: str = "/"{{- if .AuthParams }}, *{{- range $auth := .AuthParams }}, {{ $auth.ParamName }}: Optional[str] = None{{- end }}{{- end }}):
        self._base_url = base_url
{{- range $service := .Services }}
        self.{{ $service.AttrName }} = {{ $service.ClassName }}(base_url{{- range $auth := $service.AuthParams }}, {{ $auth.ParamName }}={{ $auth.ParamName }}{{- end }})
{{- end }}

{{- range $method := .DirectMethods }}
    def {{ $method.Name }}(self{{ $method.SignatureParams }}) -> {{ $method.ReturnType }}:
        return self.{{ $method.ServiceAttr }}.{{ $method.ServiceMethodName }}({{ $method.CallArgs }})

{{- end }}


def create_client(base_url: str = "/"{{- if .AuthParams }}, *{{- range $auth := .AuthParams }}, {{ $auth.ParamName }}: Optional[str] = None{{- end }}{{- end }}) -> _VirtuousClient:
    return _VirtuousClient(base_url{{- range $auth := .AuthParams }}, {{ $auth.ParamName }}={{ $auth.ParamName }}{{- end }})


def _request(method: str, url: str, headers: dict[str, str], data: Any, response_mode: str, response_type: Any) -> Any:
    req = request.Request(url, data=data, method=method, headers=headers)
    status = 0
    payload = b""
    try:
        with request.urlopen(req) as resp:
            status = resp.getcode()
            payload = resp.read()
    except error.HTTPError as err:
        status = err.code
        payload = err.read()
    if response_mode == "text":
        text = payload.decode("utf-8") if payload else ""
        if status >= 400:
            raise RuntimeError(text or f"{status} {_status_text(status)}")
        return text
    if response_mode == "bytes":
        if status >= 400:
            raise RuntimeError(f"{status} {_status_text(status)}")
        return payload
    if response_mode == "none":
        if status >= 400:
            raise RuntimeError(f"{status} {_status_text(status)}")
        return None
    text = payload.decode("utf-8") if payload else ""
    decoded = None
    if text:
        try:
            decoded = json.loads(text)
        except json.JSONDecodeError as err:
            if status >= 400:
                raise RuntimeError(f"{status} {_status_text(status)}") from err
            raise
    if status >= 400:
        if isinstance(decoded, dict) and "error" in decoded:
            raise RuntimeError(str(decoded["error"]))
        raise RuntimeError(f"{status} {_status_text(status)}")
    if response_type is None:
        return None
    return _decode_value(response_type, decoded)


def _apply_auth(url: str, headers: dict[str, str], location: str, param: str, prefix: str, value: str) -> str:
    auth_value = prefix + " " + value if prefix else value
    if location == "header":
        headers[param] = auth_value
    elif location == "query":
        url = _append_query(url, param, auth_value)
    elif location == "cookie":
        headers["Cookie"] = param + "=" + parse.quote(auth_value)
    return url


def _append_query_param(url: str, key: str, value: Any, optional: bool) -> str:
    if value is None:
        if optional:
            return url
        return _append_query(url, key, "")
    if isinstance(value, list):
        if len(value) == 0:
            if not optional:
                return _append_query(url, key, "")
            return url
        for item in value:
            if optional and item in ("", 0, False, None):
                continue
            url = _append_query(url, key, "" if item is None else str(item))
        return url
    if optional and value in ("", 0, False):
        return url
    return _append_query(url, key, str(value))


def _encode_body(body: Any, mode: str, fields: list[tuple[str, str, bool]]) -> tuple[Any, Optional[str]]:
    if mode == "form":
        return _encode_form(body, [(wire, name) for wire, name, _ in fields]).encode("utf-8"), None
    if mode == "multipart":
        return _encode_multipart(body, fields)
    return json.dumps(_encode_value(body)).encode("utf-8"), None


def _status_text(code: int) -> str:
    try:
        return http.HTTPStatus(code).phrase
    except ValueError:
        return "HTTP error"


def _decode_value(tp: Any, value: Any) -> Any:
    if value is None:
        return None
    origin = get_origin(tp)
    if origin is None:
        if is_dataclass(tp):
            return _decode_dataclass(tp, value)
        return value
    if origin is list:
        args = get_args(tp)
        elem_type = args[0] if args else Any
        return [_decode_value(elem_type, item) for item in value]
    if origin is dict:
        args = get_args(tp)
        value_type = args[1] if len(args) > 1 else Any
        return {key: _decode_value(value_type, item) for key, item in value.items()}
    if origin in (Union, types.UnionType):
        args = [arg for arg in get_args(tp) if arg is not type(None)]
        if len(args) == 1:
            return _decode_value(args[0], value)
        return value
    return value


def _decode_dataclass(cls: type[Any], data: Any) -> Any:
    if data is None:
        return None
    if not isinstance(data, dict):
        return data
    type_hints = get_type_hints(cls)
    kwargs: dict[str, Any] = {}
    for field in fields(cls):
        wire_name = field.metadata.get("wire", field.name)
        if wire_name in data:
            field_type = type_hints.get(field.name, Any)
            kwargs[field.name] = _decode_value(field_type, data[wire_name])
    return cls(**kwargs)


def _encode_value(value: Any) -> Any:
    if value is None:
        return None
    if is_dataclass(value):
        return {field.metadata.get("wire", field.name): _encode_value(getattr(value, field.name)) for field in fields(value)}
    if isinstance(value, list):
        return [_encode_value(item) for item in value]
    if isinstance(value, dict):
        return {key: _encode_value(item) for key, item in value.items()}
    return value


def _encode_form(value: Any, fields: list[tuple[str, str]]) -> str:
    encoded = _encode_value(value)
    if encoded is None:
        return ""
    if not isinstance(encoded, dict):
        return parse.urlencode({"value": str(encoded)})
    pairs: list[tuple[str, str]] = []
    items = [(wire_name, encoded.get(field_name)) for wire_name, field_name in fields] if fields else list(encoded.items())
    for key, item in items:
        if item is None:
            continue
        if isinstance(item, list):
            for child in item:
                pairs.append((key, "" if child is None else str(child)))
            continue
        pairs.append((key, str(item)))
    return parse.urlencode(pairs)


def _encode_multipart(value: Any, fields: list[tuple[str, str, bool]]) -> tuple[bytes, str]:
    boundary = "----virtuous-" + uuid.uuid4().hex
    encoded = _encode_value(value)
    if encoded is None:
        encoded = {}
    if not isinstance(encoded, dict):
        encoded = {"value": encoded}
    items = [(wire_name, encoded.get(field_name), is_file) for wire_name, field_name, is_file in fields] if fields else [(key, item, False) for key, item in encoded.items()]
    chunks: list[bytes] = []
    for key, item, is_file in items:
        if item is None:
            continue
        if isinstance(item, list):
            for child in item:
                if child is not None:
                    _append_multipart_part(chunks, boundary, key, child, is_file)
            continue
        _append_multipart_part(chunks, boundary, key, item, is_file)
    chunks.append(f"--{boundary}--\r\n".encode("utf-8"))
    return b"".join(chunks), "multipart/form-data; boundary=" + boundary


def _append_multipart_part(chunks: list[bytes], boundary: str, key: str, item: Any, is_file: bool) -> None:
    chunks.append(f"--{boundary}\r\n".encode("utf-8"))
    if is_file:
        filename, content, content_type = _multipart_file_value(key, item)
        chunks.append(
            f'Content-Disposition: form-data; name="{_multipart_quote(key)}"; filename="{_multipart_quote(filename)}"\r\n'.encode("utf-8")
        )
        chunks.append(f"Content-Type: {content_type}\r\n\r\n".encode("utf-8"))
        chunks.append(content)
        chunks.append(b"\r\n")
        return
    chunks.append(f'Content-Disposition: form-data; name="{_multipart_quote(key)}"\r\n\r\n'.encode("utf-8"))
    chunks.append(str(item).encode("utf-8"))
    chunks.append(b"\r\n")


def _multipart_file_value(key: str, item: Any) -> tuple[str, bytes, str]:
    filename = key
    content_type = "application/octet-stream"
    content = item
    if isinstance(item, tuple):
        if len(item) >= 1:
            filename = str(item[0])
        if len(item) >= 2:
            content = item[1]
        if len(item) >= 3 and item[2]:
            content_type = str(item[2])
    elif hasattr(item, "read"):
        name = getattr(item, "name", "")
        if name:
            filename = str(name).replace("\\", "/").rsplit("/", 1)[-1]
        content = item.read()
    if isinstance(content, str):
        content_bytes = content.encode("utf-8")
    elif isinstance(content, bytearray):
        content_bytes = bytes(content)
    elif isinstance(content, bytes):
        content_bytes = content
    else:
        content_bytes = str(content).encode("utf-8")
    return filename, content_bytes, content_type


def _multipart_quote(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\r", "").replace("\n", "")


def _append_query(url: str, key: str, value: str) -> str:
    parts = parse.urlsplit(url)
    query = parse.parse_qsl(parts.query, keep_blank_values=True)
    query.append((key, value))
    new_query = parse.urlencode(query)
    return parse.urlunsplit((parts.scheme, parts.netloc, parts.path, new_query, parts.fragment))
`))

type pythonClientSpec struct {
	Services      []pythonClientService
	Objects       []pythonClientObject
	AuthParams    []pythonAuthGuard
	DirectMethods []pythonClientDirectMethod
}

type pythonClientService struct {
	ClassName  string
	AttrName   string
	Methods    []pythonClientMethod
	AuthParams []pythonAuthGuard
}

type pythonClientMethod struct {
	Name               string
	SignatureParams    string
	CallArgs           string
	ReturnType         string
	HTTPMethod         string
	Path               string
	PathParams         []pythonPathParam
	HasBody            bool
	BodyOptional       bool
	BodyMode           string
	BodyFields         []pythonBodyField
	RequestMedia       string
	HasQuery           bool
	QueryParams        []pythonQueryParam
	AcceptType         string
	ResponseMode       string
	HasAuth            bool
	AuthReqs           []pythonAuthRequirement
	AuthParams         []pythonAuthGuard
	AuthError          string
	RequestType        string
	ResponseType       string
	ResponseDecodeType string
}

type pythonClientDirectMethod struct {
	Name              string
	ServiceAttr       string
	ServiceMethodName string
	SignatureParams   string
	CallArgs          string
	ReturnType        string
}

type pythonClientObject struct {
	Name   string
	Fields []pythonClientField
}

type pythonClientField struct {
	Name        string
	WireName    string
	Declaration string
	Doc         string
}

type pythonPathParam struct {
	Name    string
	VarName string
	Type    string
}

type pythonQueryParam struct {
	WireName string
	VarName  string
	Type     string
	Optional bool
}

type pythonBodyField struct {
	WireName  string
	ValueName string
	IsFile    bool
}

type pythonAuthRequirement struct {
	Guards []pythonAuthGuard
}

type pythonAuthGuard struct {
	Spec         GuardSpec
	OriginalName string
	ParamName    string
	DefaultAttr  string
	ValueName    string
}

func buildPythonClientRenderSpec(spec clientSpec) pythonClientSpec {
	typeNames := pythonObjectNameMap(spec.Objects, spec.Services)
	out := pythonClientSpec{
		Objects: pythonObjects(spec.Objects, typeNames),
	}
	authParams := pythonSpecAuthParams(spec)
	out.AuthParams = authParams
	authByName := map[string]pythonAuthGuard{}
	for _, auth := range authParams {
		authByName[auth.OriginalName] = auth
	}
	serviceAttrs := map[string]struct{}{"_base_url": {}}
	serviceClasses := map[string]struct{}{}
	directNames := map[string]struct{}{}
	for _, service := range spec.Services {
		pyService := pythonClientService{
			ClassName: clientgen.UniquePythonIdentifier("_"+service.Name+"Service", serviceClasses),
			AttrName:  clientgen.UniquePythonIdentifier(service.Name, serviceAttrs),
		}
		methodNames := map[string]struct{}{}
		for _, method := range service.Methods {
			pyMethod := pythonMethod(method, typeNames, methodNames, authByName)
			pyService.Methods = append(pyService.Methods, pyMethod)
		}
		pyService.AuthParams = pythonServiceAuthParams(pyService.Methods)
		out.Services = append(out.Services, pyService)
		for _, method := range pyService.Methods {
			out.DirectMethods = append(out.DirectMethods, pythonClientDirectMethod{
				Name:              clientgen.UniquePythonIdentifier(method.Name, directNames),
				ServiceAttr:       pyService.AttrName,
				ServiceMethodName: method.Name,
				SignatureParams:   method.SignatureParams,
				CallArgs:          method.CallArgs,
				ReturnType:        method.ReturnType,
			})
		}
	}
	return out
}

func pythonObjectNameMap(objects []clientObject, services []clientService) map[string]string {
	used := pythonReservedModuleNames(services)
	out := make(map[string]string, len(objects))
	for _, object := range objects {
		out[object.Name] = clientgen.UniquePythonIdentifier(object.Name, used)
	}
	return out
}

func pythonReservedModuleNames(services []clientService) map[string]struct{} {
	names := []string{
		"Any",
		"Optional",
		"Union",
		"_VirtuousClient",
		"_append_multipart_part",
		"_append_query",
		"_append_query_param",
		"_apply_auth",
		"_decode_dataclass",
		"_decode_value",
		"_encode_body",
		"_encode_form",
		"_encode_multipart",
		"_encode_value",
		"_multipart_file_value",
		"_multipart_quote",
		"_request",
		"_status_text",
		"create_client",
		"dataclass",
		"datetime",
		"dict",
		"error",
		"field",
		"fields",
		"get_args",
		"get_origin",
		"get_type_hints",
		"http",
		"id",
		"int",
		"is_dataclass",
		"json",
		"list",
		"object",
		"parse",
		"request",
		"set",
		"str",
		"types",
		"type",
		"uuid",
	}
	out := make(map[string]struct{}, len(names))
	for _, name := range names {
		out[name] = struct{}{}
	}
	serviceNames := map[string]struct{}{}
	for _, service := range services {
		serviceNames[clientgen.PythonIdentifier("_"+service.Name+"Service")] = struct{}{}
	}
	for name := range serviceNames {
		out[name] = struct{}{}
	}
	return out
}

func pythonObjects(objects []clientObject, typeNames map[string]string) []pythonClientObject {
	out := make([]pythonClientObject, 0, len(objects))
	for _, object := range objects {
		pyObject := pythonClientObject{Name: typeNames[object.Name]}
		fieldNames := map[string]struct{}{}
		for _, field := range object.Fields {
			name := clientgen.UniquePythonIdentifier(field.Name, fieldNames)
			fieldType := pythonTypeName(field.Type, typeNames)
			pyObject.Fields = append(pyObject.Fields, pythonClientField{
				Name:        name,
				WireName:    field.Name,
				Declaration: pythonFieldDeclaration(name, field.Name, fieldType, field.Optional || field.Nullable),
				Doc:         field.Doc,
			})
		}
		out = append(out, pyObject)
	}
	return out
}

func pythonFieldDeclaration(name, wireName, fieldType string, optional bool) string {
	if fieldType == "" {
		fieldType = "Any"
	}
	typeExpr := fieldType
	if optional {
		typeExpr = "Optional[" + fieldType + "]"
	}
	if name == wireName {
		if optional {
			return name + ": " + typeExpr + " = None"
		}
		return name + ": " + typeExpr
	}
	meta := `metadata={"wire": ` + clientgen.PythonStringLiteral(wireName) + `}`
	if optional {
		return name + ": " + typeExpr + " = field(default=None, " + meta + ")"
	}
	return name + ": " + typeExpr + " = field(" + meta + ")"
}

func pythonMethod(method clientMethod, typeNames map[string]string, methodNames map[string]struct{}, authByName map[string]pythonAuthGuard) pythonClientMethod {
	usedParams := map[string]struct{}{"self": {}}
	if method.HasBody {
		usedParams["body"] = struct{}{}
	}
	pyMethod := pythonClientMethod{
		Name:         clientgen.UniquePythonIdentifier(method.OperationID, methodNames),
		HTTPMethod:   method.HTTPMethod,
		Path:         method.Path,
		HasBody:      method.HasBody,
		BodyOptional: method.BodyOptional,
		BodyMode:     method.BodyMode,
		RequestMedia: method.RequestMedia,
		HasQuery:     method.HasQuery,
		AcceptType:   method.AcceptType,
		ResponseMode: method.ResponseMode,
		HasAuth:      method.HasAuth,
		RequestType:  pythonTypeName(method.RequestType, typeNames),
		ResponseType: pythonTypeName(method.ResponseType, typeNames),
	}
	pyMethod.ResponseDecodeType = pythonRuntimeTypeName(pyMethod.ResponseType)
	pyMethod.ReturnType = pythonReturnType(pyMethod)
	for _, param := range method.PathParams {
		pyMethod.PathParams = append(pyMethod.PathParams, pythonPathParam{
			Name:    param.Name,
			VarName: clientgen.UniquePythonIdentifier(param.Name, usedParams),
			Type:    param.Type,
		})
	}
	for _, param := range method.QueryParams {
		pyMethod.QueryParams = append(pyMethod.QueryParams, pythonQueryParam{
			WireName: param.Name,
			VarName:  clientgen.UniquePythonIdentifier(pythonSnakeName(param.Name), usedParams),
			Type:     param.Type,
			Optional: param.Optional,
		})
	}
	for _, field := range method.BodyFields {
		pyMethod.BodyFields = append(pyMethod.BodyFields, pythonBodyField{
			WireName:  field.WireName,
			ValueName: field.Name,
			IsFile:    field.IsFile,
		})
	}
	authNames := map[string]string{}
	for _, auth := range method.AuthParams {
		defaultAuth := authByName[auth.ParamName]
		name := clientgen.UniquePythonIdentifier(defaultAuth.ParamName, usedParams)
		authNames[auth.ParamName] = name
		pyMethod.AuthParams = append(pyMethod.AuthParams, pythonAuthGuard{
			Spec:         auth.Spec,
			OriginalName: auth.ParamName,
			ParamName:    name,
			DefaultAttr:  defaultAuth.DefaultAttr,
		})
	}
	for _, req := range method.AuthReqs {
		pyReq := pythonAuthRequirement{Guards: make([]pythonAuthGuard, 0, len(req.Guards))}
		for _, guard := range req.Guards {
			defaultAuth := authByName[guard.ParamName]
			pyReq.Guards = append(pyReq.Guards, pythonAuthGuard{
				Spec:         guard.Spec,
				OriginalName: guard.ParamName,
				ParamName:    authNames[guard.ParamName],
				DefaultAttr:  defaultAuth.DefaultAttr,
				ValueName:    clientgen.PythonIdentifier(authNames[guard.ParamName] + "_value"),
			})
		}
		pyMethod.AuthReqs = append(pyMethod.AuthReqs, pyReq)
	}
	pyMethod.AuthError = pythonAuthError(pyMethod.AuthReqs)
	pyMethod.SignatureParams = pythonMethodSignatureParams(pyMethod)
	pyMethod.CallArgs = pythonMethodCallArgs(pyMethod)
	return pyMethod
}

func pythonSpecAuthParams(spec clientSpec) []pythonAuthGuard {
	used := map[string]struct{}{"self": {}, "base_url": {}}
	seen := map[string]struct{}{}
	var out []pythonAuthGuard
	for _, service := range spec.Services {
		for _, method := range service.Methods {
			for _, auth := range method.AuthParams {
				if _, ok := seen[auth.ParamName]; ok {
					continue
				}
				seen[auth.ParamName] = struct{}{}
				name := clientgen.UniquePythonIdentifier(pythonSnakeName(auth.ParamName), used)
				out = append(out, pythonAuthGuard{
					Spec:         auth.Spec,
					OriginalName: auth.ParamName,
					ParamName:    name,
					DefaultAttr:  "_" + name,
				})
			}
		}
	}
	return out
}

func pythonServiceAuthParams(methods []pythonClientMethod) []pythonAuthGuard {
	seen := map[string]struct{}{}
	var out []pythonAuthGuard
	for _, method := range methods {
		for _, auth := range method.AuthParams {
			if _, ok := seen[auth.OriginalName]; ok {
				continue
			}
			seen[auth.OriginalName] = struct{}{}
			out = append(out, auth)
		}
	}
	return out
}

func pythonReturnType(method pythonClientMethod) string {
	if method.ResponseMode == "none" {
		return "None"
	}
	if method.ResponseType != "" {
		return method.ResponseType
	}
	return "Any"
}

func pythonMethodSignatureParams(method pythonClientMethod) string {
	var parts []string
	for _, param := range method.PathParams {
		parts = append(parts, param.VarName+": "+param.Type)
	}
	var keywords []string
	for _, param := range method.QueryParams {
		if !param.Optional {
			keywords = append(keywords, param.VarName+": "+param.Type)
		}
	}
	if method.HasBody {
		bodyType := method.RequestType
		if bodyType == "" {
			bodyType = "Any"
		}
		keywords = append(keywords, "body: Optional["+bodyType+"] = None")
	}
	for _, param := range method.QueryParams {
		if param.Optional {
			keywords = append(keywords, param.VarName+": Optional["+param.Type+"] = None")
		}
	}
	for _, auth := range method.AuthParams {
		keywords = append(keywords, auth.ParamName+": Optional[str] = None")
	}
	var out strings.Builder
	for _, part := range parts {
		out.WriteString(", ")
		out.WriteString(part)
	}
	if len(keywords) > 0 {
		out.WriteString(", *")
		for _, part := range keywords {
			out.WriteString(", ")
			out.WriteString(part)
		}
	}
	return out.String()
}

func pythonMethodCallArgs(method pythonClientMethod) string {
	var args []string
	for _, param := range method.PathParams {
		args = append(args, param.VarName)
	}
	if method.HasBody {
		args = append(args, "body=body")
	}
	for _, param := range method.QueryParams {
		args = append(args, param.VarName+"="+param.VarName)
	}
	for _, auth := range method.AuthParams {
		args = append(args, auth.ParamName+"="+auth.ParamName)
	}
	return strings.Join(args, ", ")
}

func pythonAuthError(reqs []pythonAuthRequirement) string {
	var alternatives []string
	for _, req := range reqs {
		var names []string
		for _, guard := range req.Guards {
			names = append(names, guard.ParamName)
		}
		if len(names) > 0 {
			alternatives = append(alternatives, strings.Join(names, " and "))
		}
	}
	return strings.Join(alternatives, " or ")
}

func pythonSnakeName(name string) string {
	var out []rune
	var prev rune
	for i, r := range name {
		if r == '-' || r == ' ' || r == '.' || r == '/' {
			if len(out) > 0 && out[len(out)-1] != '_' {
				out = append(out, '_')
			}
			prev = '_'
			continue
		}
		if r == '_' {
			if len(out) > 0 && out[len(out)-1] != '_' {
				out = append(out, '_')
			}
			prev = '_'
			continue
		}
		if unicode.IsUpper(r) {
			if i > 0 && prev != '_' && (unicode.IsLower(prev) || unicode.IsDigit(prev)) {
				out = append(out, '_')
			}
			out = append(out, unicode.ToLower(r))
			prev = r
			continue
		}
		out = append(out, unicode.ToLower(r))
		prev = r
	}
	value := strings.Trim(string(out), "_")
	if value == "" {
		return "_"
	}
	return value
}

func pythonTypeName(typeName string, names map[string]string) string {
	out := typeName
	for oldName, newName := range names {
		if oldName == newName {
			continue
		}
		out = strings.ReplaceAll(out, `"`+oldName+`"`, `"`+newName+`"`)
	}
	return out
}

func pythonRuntimeTypeName(typeName string) string {
	if typeName == "" {
		return ""
	}
	return strings.ReplaceAll(typeName, `"`, "")
}

// WriteClientPY writes a generated Python client to w.
func (r *Router) WriteClientPY(w io.Writer) error {
	body, err := r.clientPYBody()
	if err != nil {
		return err
	}
	hash := clientgen.HashBytes(body)
	if _, err := io.WriteString(w, "# Virtuous client hash: "+hash+"\n"); err != nil {
		return err
	}
	_, err = w.Write(body)
	return err
}

// WriteClientPYFile writes a generated Python client to the file at path.
func (r *Router) WriteClientPYFile(path string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return r.WriteClientPY(f)
}

// WriteClientPYHash writes the hash of the Python client output to w.
func (r *Router) WriteClientPYHash(w io.Writer) error {
	hash, err := r.clientPYHash()
	if err != nil {
		return err
	}
	_, err = io.WriteString(w, hash)
	return err
}

// ServeClientPY writes a generated Python client as an HTTP response.
func (r *Router) ServeClientPY(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "text/x-python; charset=utf-8")
	if err := r.WriteClientPY(w); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

// ServeClientPYHash writes the hash of the Python client as an HTTP response.
func (r *Router) ServeClientPYHash(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	if err := r.WriteClientPYHash(w); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

func (r *Router) clientPYBody() ([]byte, error) {
	spec, err := buildPythonClientSpec(r.Routes(), r.typeOverrides)
	if err != nil {
		return nil, err
	}
	return clientgen.RenderTemplate(clientPyTemplate, buildPythonClientRenderSpec(spec))
}

func (r *Router) clientPYHash() (string, error) {
	body, err := r.clientPYBody()
	if err != nil {
		return "", err
	}
	return clientgen.HashBytes(body), nil
}
