package httpapi

import (
	"github.com/swetjen/virtuous/internal/clientgen"
	"io"
	"net/http"
	"os"
	"text/template"
)

var clientTSTemplate = template.Must(template.New("virtuous-ts").Parse(`// Code generated by Virtuous; DO NOT EDIT.

export type AuthOptions = {
	auth?: string
	[key: string]: string | undefined
}
{{range $object := .Objects}}
export interface {{$object.Name}} {
{{- range $field := $object.Fields}}
	{{$field.Name}}{{if $field.Optional}}?{{end}}: {{$field.Type}}{{if $field.Nullable}} | null{{end}};
{{- end}}
}
{{end}}
export function createClient(basepath: string = "/") {
	return {
{{- range $service := .Services }}
		{{ $service.Name }}: {
{{- range $method := $service.Methods }}
			async {{ $method.Name }}({{ if $method.PathParams }}pathParams: { {{- range $param := $method.PathParams }}{{ $param.Name }}: {{ $param.Type }}; {{- end }} }, {{ end }}{{ if $method.HasBody }}request{{ if $method.BodyOptional }}?{{ end }}: {{ $method.RequestType }}, {{ end }}{{ if $method.HasQuery }}query?: { {{- range $param := $method.QueryParams }}{{ $param.Name }}{{ if $param.Optional }}?{{ end }}: {{ $param.Type }}; {{- end }} }, {{ end }}options?: AuthOptions): Promise<{{ if eq $method.ResponseMode "none" }}void{{ else if $method.ResponseType }}{{ $method.ResponseType }}{{ else }}unknown{{ end }}> {
				const headers: Record<string, string> = {
					"Accept": "{{ $method.AcceptType }}",
{{- if $method.HasBody }}
					"Content-Type": "{{ $method.RequestMedia }}",
{{- end }}
				}
				let url = basepath + "{{ $method.Path }}"
{{- if $method.PathParams }}
				if (!pathParams) {
					throw new Error("pathParams is required")
				}
{{- range $param := $method.PathParams }}
				url = url.replace("{{ printf "{%s}" $param.Name }}", encodeURIComponent(String(pathParams.{{ $param.Name }})))
{{- end }}
{{- end }}
{{- if $method.HasQuery }}
				const queryParts: string[] = []
				const appendQuery = (key: string, value: unknown, optional: boolean) => {
					if (value === undefined || value === null) {
						if (optional) {
							return
						}
						queryParts.push(encodeURIComponent(key) + "=")
						return
					}
					if (Array.isArray(value)) {
						if (value.length === 0) {
							if (!optional) {
								queryParts.push(encodeURIComponent(key) + "=")
							}
							return
						}
						for (const item of value) {
							if (optional && (item === "" || item === 0 || item === false || item === null || item === undefined)) {
								continue
							}
							const encoded = item === null || item === undefined ? "" : String(item)
							queryParts.push(encodeURIComponent(key) + "=" + encodeURIComponent(encoded))
						}
						return
					}
					if (optional && (value === "" || value === 0 || value === false)) {
						return
					}
					queryParts.push(encodeURIComponent(key) + "=" + encodeURIComponent(String(value)))
				}
{{- range $param := $method.QueryParams }}
				appendQuery("{{ $param.Name }}", query && query.{{ $param.Name }}, {{ if $param.Optional }}true{{ else }}false{{ end }})
{{- end }}
				if (queryParts.length > 0) {
					const sep = url.includes("?") ? "&" : "?"
					url = url + sep + queryParts.join("&")
				}
{{- end }}
{{- if $method.HasAuth }}
				const applyAuth = (location: string, param: string, prefix: string, value: string) => {
					const authValue = prefix ? prefix + " " + value : value
					if (location === "header") {
						headers[param] = authValue
					} else if (location === "query") {
						const sep = url.includes("?") ? "&" : "?"
						url = url + sep + encodeURIComponent(param) + "=" + encodeURIComponent(authValue)
					} else if (location === "cookie") {
						document.cookie = param + "=" + encodeURIComponent(authValue) + "; path=/"
					}
				}
				let authApplied = false
{{- range $req := $method.AuthReqs }}
				if (!authApplied) {
{{- if eq (len $req.Guards) 1 }}
{{- range $guard := $req.Guards }}
					const {{ $guard.ParamName }}Value = options && (options.{{ $guard.ParamName }} || options.auth)
					if ({{ $guard.ParamName }}Value) {
						applyAuth("{{ $guard.Spec.In }}", "{{ $guard.Spec.Param }}", "{{ $guard.Spec.Prefix }}", {{ $guard.ParamName }}Value)
						authApplied = true
					}
{{- end }}
{{- else }}
					const hasAuthValues = true{{ range $guard := $req.Guards }} && !!(options && options.{{ $guard.ParamName }}){{ end }}
					if (hasAuthValues) {
{{- range $guard := $req.Guards }}
						applyAuth("{{ $guard.Spec.In }}", "{{ $guard.Spec.Param }}", "{{ $guard.Spec.Prefix }}", options!.{{ $guard.ParamName }}!)
{{- end }}
						authApplied = true
					}
{{- end }}
				}
{{- end }}
{{- end }}
{{- if and $method.HasBody (eq $method.BodyMode "form") }}
				const encodeForm = (value: unknown): string => {
					const form = new URLSearchParams()
					const appendForm = (key: string, item: unknown) => {
						if (item === undefined || item === null) {
							return
						}
						if (Array.isArray(item)) {
							for (const child of item) {
								if (child !== undefined && child !== null) {
									form.append(key, String(child))
								}
							}
							return
						}
						form.append(key, String(item))
					}
					const data = (value || {}) as Record<string, unknown>
{{- if $method.BodyFields }}
{{- range $field := $method.BodyFields }}
					appendForm("{{ $field.WireName }}", data.{{ $field.Name }})
{{- end }}
{{- else }}
					for (const [key, item] of Object.entries(data)) {
						appendForm(key, item)
					}
{{- end }}
					return form.toString()
				}
{{- end }}
				const response = await fetch(url, {
					method: "{{ $method.HTTPMethod }}",
					headers,
{{- if $method.HasCookieAuth }}
					credentials: "same-origin",
{{- end }}
{{- if $method.HasBody }}
{{- if $method.BodyOptional }}
					body: request === undefined || request === null ? undefined : {{ if eq $method.BodyMode "form" }}encodeForm(request){{ else }}JSON.stringify(request){{ end }},
{{- else }}
					body: {{ if eq $method.BodyMode "form" }}encodeForm(request || {}){{ else }}JSON.stringify(request || {}){{ end }},
{{- end }}
{{- end }}
				})
{{- if eq $method.ResponseMode "json" }}
				const text = await response.text()
				let json: {{ if $method.ResponseType }}{{ $method.ResponseType }}{{ else }}Record<string, unknown>{{ end }} | null = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new Error(response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					const errorBody = json as { error?: string } | null
					if (errorBody && errorBody.error) {
						throw new Error(errorBody.error)
					}
					throw new Error(response.status + " " + response.statusText)
				}
				return json as {{ if $method.ResponseType }}{{ $method.ResponseType }}{{ else }}unknown{{ end }}
{{- else if eq $method.ResponseMode "text" }}
				const text = await response.text()
				if (!response.ok) {
					throw new Error(text || (response.status + " " + response.statusText))
				}
				return text as {{ if $method.ResponseType }}{{ $method.ResponseType }}{{ else }}string{{ end }}
{{- else if eq $method.ResponseMode "bytes" }}
				const raw = await response.arrayBuffer()
				if (!response.ok) {
					throw new Error(response.status + " " + response.statusText)
				}
				return new Uint8Array(raw) as {{ if $method.ResponseType }}{{ $method.ResponseType }}{{ else }}Uint8Array{{ end }}
{{- else }}
				if (!response.ok) {
					throw new Error(response.status + " " + response.statusText)
				}
				return
{{- end }}
			},
{{- end }}
		},
{{- end }}
	}
}
`))

// WriteClientTS writes a generated TS client to w.
func (r *Router) WriteClientTS(w io.Writer) error {
	body, err := r.clientTSBody()
	if err != nil {
		return err
	}
	hash := clientgen.HashBytes(body)
	if _, err := io.WriteString(w, "// Virtuous client hash: "+hash+"\n"); err != nil {
		return err
	}
	_, err = w.Write(body)
	return err
}

// WriteClientTSFile writes a generated TS client to the file at path.
func (r *Router) WriteClientTSFile(path string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return r.WriteClientTS(f)
}

// WriteClientTSHash writes the hash of the TS client output to w.
func (r *Router) WriteClientTSHash(w io.Writer) error {
	hash, err := r.clientTSHash()
	if err != nil {
		return err
	}
	_, err = io.WriteString(w, hash)
	return err
}

// ServeClientTS writes a generated TS client as an HTTP response.
func (r *Router) ServeClientTS(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "application/typescript")
	if err := r.WriteClientTS(w); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

// ServeClientTSHash writes the hash of the TS client as an HTTP response.
func (r *Router) ServeClientTSHash(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	if err := r.WriteClientTSHash(w); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

func (r *Router) clientTSBody() ([]byte, error) {
	spec, err := buildClientSpec(r.Routes(), r.typeOverrides)
	if err != nil {
		return nil, err
	}
	return clientgen.RenderTemplate(clientTSTemplate, spec)
}

func (r *Router) clientTSHash() (string, error) {
	body, err := r.clientTSBody()
	if err != nil {
		return "", err
	}
	return clientgen.HashBytes(body), nil
}
