package httpapi

import (
	"github.com/swetjen/virtuous/internal/clientgen"
	"io"
	"net/http"
	"os"
	"text/template"
)

var clientJSTemplate = template.Must(template.New("virtuous-js").Parse(`// Code generated by Virtuous; DO NOT EDIT.

/**
 * @typedef {Object} AuthOptions
 * @property {string} [auth]
 */

// Type definitions
{{- range $object := .Objects }}
/**
 * @typedef {Object} {{ $object.Name }}
{{- range $field := $object.Fields }}
 * @property{{- if $field.Nullable }} {{ printf "{%s|null}" $field.Type }}{{ else }} {{ printf "{%s}" $field.Type }}{{ end }} {{ if $field.Optional }}[{{ $field.Name }}]{{ else }}{{ $field.Name }}{{ end }}{{ if $field.Doc }} - {{ $field.Doc }}{{ end }}
{{- end }}
 */

{{- end }}

/**
 * @param {string} [basepath="/"]
 * @returns {object}
 */
export function createClient(basepath = "/") {
	return {
{{- range $service := .Services }}
		{{ $service.Name }}: {
{{- range $method := $service.Methods }}
			/**
{{- if $method.Summary }}
			 * {{ $method.Summary }}
			 *
{{- end }}
{{- if $method.PathParams }}
			 * @param {Object} pathParams
{{- end }}
{{- if $method.HasBody }}
			 * @param { {{- if $method.RequestType }}{{ $method.RequestType }}{{ else }}any{{ end }} }{{ if $method.BodyOptional }} [request]{{ else }} request{{ end }}
{{- end }}
{{- if $method.HasQuery }}
			 * @param {Object} [query]
{{- range $param := $method.QueryParams }}
			 * @param { {{- $param.Type }} }{{ if $param.Optional }} [{{ printf "query.%s" $param.Name }}]{{ else }} {{ printf "query.%s" $param.Name }}{{ end }}{{ if $param.Doc }} - {{ $param.Doc }}{{ end }}
{{- end }}
{{- end }}
			 * @param {AuthOptions} [options]
			 * @returns {Promise<{{- if eq $method.ResponseMode "none" }}void{{ else if $method.ResponseType }}{{ $method.ResponseType }}{{ else }}any{{ end }}>}
				 */
				async {{ $method.Name }}({{ if $method.PathParams }}pathParams, {{ end }}{{ if $method.HasBody }}request, {{ end }}{{ if $method.HasQuery }}query, {{ end }}options) {
				const headers = {
					"Accept": "{{ $method.AcceptType }}",
{{- if $method.HasBody }}
						"Content-Type": "{{ $method.RequestMedia }}",
{{- end }}
				}
				let url = basepath + "{{ $method.Path }}"
{{- if $method.PathParams }}
				if (!pathParams) {
					throw new Error("pathParams is required")
				}
{{- range $param := $method.PathParams }}
				url = url.replace("{{ printf "{%s}" $param.Name }}", encodeURIComponent(String(pathParams.{{ $param.Name }})))
{{- end }}
{{- end }}
{{- if $method.HasQuery }}
				const queryParts = []
				const appendQuery = (key, value, optional) => {
					if (value === undefined || value === null) {
						if (optional) {
							return
						}
						queryParts.push(encodeURIComponent(key) + "=")
						return
					}
					if (Array.isArray(value)) {
						if (value.length === 0) {
							if (!optional) {
								queryParts.push(encodeURIComponent(key) + "=")
							}
							return
						}
						for (const item of value) {
							if (optional && (item === "" || item === 0 || item === false || item === null || item === undefined)) {
								continue
							}
							const encoded = item === null || item === undefined ? "" : String(item)
							queryParts.push(encodeURIComponent(key) + "=" + encodeURIComponent(encoded))
						}
						return
					}
					if (optional && (value === "" || value === 0 || value === false)) {
						return
					}
					queryParts.push(encodeURIComponent(key) + "=" + encodeURIComponent(String(value)))
				}
{{- range $param := $method.QueryParams }}
				appendQuery("{{ $param.Name }}", query && query.{{ $param.Name }}, {{ if $param.Optional }}true{{ else }}false{{ end }})
{{- end }}
				if (queryParts.length > 0) {
					const sep = url.includes("?") ? "&" : "?"
					url = url + sep + queryParts.join("&")
				}
{{- end }}
{{- if $method.HasAuth }}
				const applyAuth = (location, param, prefix, value) => {
					const authValue = prefix ? prefix + " " + value : value
					if (location === "header") {
						headers[param] = authValue
					} else if (location === "query") {
						const sep = url.includes("?") ? "&" : "?"
						url = url + sep + encodeURIComponent(param) + "=" + encodeURIComponent(authValue)
					} else if (location === "cookie") {
						document.cookie = param + "=" + encodeURIComponent(authValue) + "; path=/"
					}
				}
				let authApplied = false
{{- range $req := $method.AuthReqs }}
				if (!authApplied) {
{{- if eq (len $req.Guards) 1 }}
{{- range $guard := $req.Guards }}
					const {{ $guard.ParamName }}Value = options && (options.{{ $guard.ParamName }} || options.auth)
					if ({{ $guard.ParamName }}Value) {
						applyAuth("{{ $guard.Spec.In }}", "{{ $guard.Spec.Param }}", "{{ $guard.Spec.Prefix }}", {{ $guard.ParamName }}Value)
						authApplied = true
					}
{{- end }}
{{- else }}
					const hasAuthValues = true{{ range $guard := $req.Guards }} && !!(options && options.{{ $guard.ParamName }}){{ end }}
					if (hasAuthValues) {
{{- range $guard := $req.Guards }}
						applyAuth("{{ $guard.Spec.In }}", "{{ $guard.Spec.Param }}", "{{ $guard.Spec.Prefix }}", options.{{ $guard.ParamName }})
{{- end }}
						authApplied = true
					}
{{- end }}
				}
{{- end }}
{{- end }}
{{- if and $method.HasBody (eq $method.BodyMode "form") }}
				const encodeForm = (value) => {
					const form = new URLSearchParams()
					const appendForm = (key, item) => {
						if (item === undefined || item === null) {
							return
						}
						if (Array.isArray(item)) {
							for (const child of item) {
								if (child !== undefined && child !== null) {
									form.append(key, String(child))
								}
							}
							return
						}
						form.append(key, String(item))
					}
					const data = value || {}
{{- if $method.BodyFields }}
{{- range $field := $method.BodyFields }}
					appendForm("{{ $field.WireName }}", data.{{ $field.Name }})
{{- end }}
{{- else }}
					for (const [key, item] of Object.entries(data)) {
						appendForm(key, item)
					}
{{- end }}
					return form.toString()
				}
{{- end }}
				const response = await fetch(url, {
					method: "{{ $method.HTTPMethod }}",
					headers,
{{- if $method.HasCookieAuth }}
					credentials: "same-origin",
{{- end }}
{{- if $method.HasBody }}
{{- if $method.BodyOptional }}
					body: request === undefined || request === null ? undefined : {{ if eq $method.BodyMode "form" }}encodeForm(request){{ else }}JSON.stringify(request){{ end }},
{{- else }}
					body: {{ if eq $method.BodyMode "form" }}encodeForm(request || {}){{ else }}JSON.stringify(request || {}){{ end }},
{{- end }}
{{- end }}
				})
{{- if eq $method.ResponseMode "json" }}
				const text = await response.text()
				let json = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new Error(response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					if (json && json.error) {
						throw new Error(json.error)
					}
					throw new Error(response.status + " " + response.statusText)
				}
				return json || {}
{{- else if eq $method.ResponseMode "text" }}
				const text = await response.text()
				if (!response.ok) {
					throw new Error(text || (response.status + " " + response.statusText))
				}
				return text
{{- else if eq $method.ResponseMode "bytes" }}
				const raw = await response.arrayBuffer()
				if (!response.ok) {
					throw new Error(response.status + " " + response.statusText)
				}
				return new Uint8Array(raw)
{{- else }}
				if (!response.ok) {
					throw new Error(response.status + " " + response.statusText)
				}
				return
{{- end }}
			},
{{- end }}
		},
{{- end }}
	}
}
`))

// WriteClientJS writes a generated JS client to w.
func (r *Router) WriteClientJS(w io.Writer) error {
	body, err := r.clientJSBody()
	if err != nil {
		return err
	}
	hash := clientgen.HashBytes(body)
	if _, err := io.WriteString(w, "// Virtuous client hash: "+hash+"\n"); err != nil {
		return err
	}
	_, err = w.Write(body)
	return err
}

// WriteClientJSFile writes a generated JS client to the file at path.
func (r *Router) WriteClientJSFile(path string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return r.WriteClientJS(f)
}

// WriteClientJSHash writes the hash of the JS client output to w.
func (r *Router) WriteClientJSHash(w io.Writer) error {
	hash, err := r.clientJSHash()
	if err != nil {
		return err
	}
	_, err = io.WriteString(w, hash)
	return err
}

// ServeClientJS writes a generated JS client as an HTTP response.
func (r *Router) ServeClientJS(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "application/javascript")
	if err := r.WriteClientJS(w); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

// ServeClientJSHash writes the hash of the JS client as an HTTP response.
func (r *Router) ServeClientJSHash(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	if err := r.WriteClientJSHash(w); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

func (r *Router) clientJSBody() ([]byte, error) {
	spec, err := buildClientSpec(r.Routes(), r.typeOverrides)
	if err != nil {
		return nil, err
	}
	return clientgen.RenderTemplate(clientJSTemplate, spec)
}

func (r *Router) clientJSHash() (string, error) {
	body, err := r.clientJSBody()
	if err != nil {
		return "", err
	}
	return clientgen.HashBytes(body), nil
}
