package httpapi

import (
	"io"
	"net/http"
	"os"
	"text/template"

	"github.com/swetjen/virtuous/internal/clientgen"
)

var clientTSTemplate = template.Must(template.New("virtuous-ts").Parse(`// Code generated by Virtuous; DO NOT EDIT.

export type RequestOptions = {
	signal?: AbortSignal
	auth?: RequestAuth
}

export type RequestAuth = {
	auth?: string
{{- range $auth := .AuthParams }}
	{{ $auth.ParamName }}?: string
{{- end }}
	[key: string]: string | undefined
}

type MaybePromise<T> = T | Promise<T>
export type AuthProvider = RequestAuth | (() => MaybePromise<RequestAuth | null | undefined>)

export type ClientOptions = {
	baseUrl?: string
	auth?: AuthProvider
}

export class AuthNotReadyError extends Error {
	route: string
	constructor(route: string) {
		super("Auth is required for " + route + " but no auth value is available")
		this.name = "AuthNotReadyError"
		this.route = route
	}
}
{{range $object := .Objects}}
export interface {{$object.Name}} {
{{- range $field := $object.Fields}}
	{{$field.Name}}{{if $field.Optional}}?{{end}}: {{$field.Type}}{{if $field.Nullable}} | null{{end}};
{{- end}}
}
{{end}}
{{- range $service := .Services }}{{- range $method := $service.Methods }}
{{- if $method.PathParams }}
export type {{ $method.PathParamsType }} = { {{- range $param := $method.PathParams }}{{ $param.Name }}: {{ $param.Type }}; {{- end }} }
{{ end -}}
{{- if $method.HasQuery }}
export type {{ $method.QueryParamsType }} = { {{- range $param := $method.QueryParams }}{{ $param.Name }}{{ if $param.Optional }}?{{ end }}: {{ $param.Type }}; {{- end }} }
{{ end -}}
{{- end }}{{- end }}
export function createClient(options: ClientOptions = {}) {
	let clientOptions: ClientOptions = {
		baseUrl: options.baseUrl ?? "/",
		auth: options.auth,
	}
	return {
		configure(nextOptions: ClientOptions) {
			clientOptions = { ...clientOptions, ...nextOptions }
		},
{{- range $service := .Services }}
		{{ $service.Name }}: {
{{- range $method := $service.Methods }}
			async {{ $method.Name }}({{ if $method.PathParams }}pathParams: {{ $method.PathParamsType }}, {{ end }}{{ if $method.HasBody }}request{{ if $method.BodyOptional }}?{{ end }}: {{ $method.RequestType }}, {{ end }}{{ if $method.HasQuery }}query?: {{ $method.QueryParamsType }}, {{ end }}options?: RequestOptions): Promise<{{ if eq $method.ResponseMode "none" }}void{{ else if $method.ResponseType }}{{ $method.ResponseType }}{{ else }}unknown{{ end }}> {
				let path = "{{ $method.Path }}"
{{- if $method.PathParams }}
				if (!pathParams) {
					throw new Error("pathParams is required")
				}
{{- range $param := $method.PathParams }}
				path = path.replace("{{ printf "{%s}" $param.Name }}", encodeURIComponent(String(pathParams.{{ $param.Name }})))
{{- end }}
{{- end }}
				return _request<{{ if eq $method.ResponseMode "none" }}void{{ else if $method.ResponseType }}{{ $method.ResponseType }}{{ else }}unknown{{ end }}>(clientOptions, {
					method: "{{ $method.HTTPMethod }}",
					path,
					accept: "{{ $method.AcceptType }}",
					response: "{{ $method.ResponseMode }}",
{{- if $method.HasBody }}
					bodyMode: "{{ $method.BodyMode }}",
{{- if ne $method.BodyMode "multipart" }}
					contentType: "{{ $method.RequestMedia }}",
{{- end }}
{{- if $method.BodyOptional }}
					body: request === undefined || request === null ? undefined : request,
{{- else }}
					body: request || {},
{{- end }}
{{- if $method.BodyFields }}
					bodyFields: [
{{- range $field := $method.BodyFields }}
						["{{ $field.WireName }}", "{{ $field.Name }}", {{ if $field.IsFile }}true{{ else }}false{{ end }}],
{{- end }}
					],
{{- end }}
{{- end }}
{{- if $method.HasQuery }}
					query: [
{{- range $param := $method.QueryParams }}
						["{{ $param.Name }}", query?.{{ $param.Name }}, {{ if $param.Optional }}true{{ else }}false{{ end }}],
{{- end }}
					],
{{- end }}
{{- if $method.HasAuth }}
					auth: [
{{- range $req := $method.AuthReqs }}
						[
{{- if eq (len $req.Guards) 1 }}{{- range $guard := $req.Guards }}
							{ name: "{{ $guard.ParamName }}", in: "{{ $guard.Spec.In }}", param: "{{ $guard.Spec.Param }}", prefix: "{{ $guard.Spec.Prefix }}", generic: {{ if eq (len $method.AuthReqs) 1 }}true{{ else }}false{{ end }} },
{{- end }}{{- else }}{{- range $guard := $req.Guards }}
							{ name: "{{ $guard.ParamName }}", in: "{{ $guard.Spec.In }}", param: "{{ $guard.Spec.Param }}", prefix: "{{ $guard.Spec.Prefix }}" },
{{- end }}{{- end }}
						],
{{- end }}
					],
{{- end }}
{{- if $method.HasCookieAuth }}
					cookie: true,
{{- end }}
					options,
				})
			},
{{- end }}
		},
{{- end }}
	}
}

type QueryItem = [string, unknown, boolean]
type BodyField = [string, string, boolean]
type AuthGuard = { name: string; in: string; param: string; prefix: string; generic?: boolean }
type RequestConfig = {
	method: string
	path: string
	accept: string
	response: string
	contentType?: string
	body?: unknown
	bodyMode?: string
	bodyFields?: BodyField[]
	query?: QueryItem[]
	auth?: AuthGuard[][]
	cookie?: boolean
	options?: RequestOptions
}

async function _request<T>(clientOptions: ClientOptions, config: RequestConfig): Promise<T> {
	const headers: Record<string, string> = { "Accept": config.accept }
	if (config.contentType) {
		headers["Content-Type"] = config.contentType
	}
	let url = (clientOptions.baseUrl ?? "/") + config.path
	for (const item of config.query ?? []) {
		url = _appendQuery(url, item[0], item[1], item[2])
	}
	if (config.auth) {
		const auth = config.options?.auth ?? await _resolveAuth(clientOptions.auth)
		let applied = false
		for (const requirement of config.auth) {
			const values: Array<[AuthGuard, string]> = []
			for (const guard of requirement) {
				const value = auth && (auth[guard.name] || (guard.generic ? auth.auth : undefined))
				if (!value) {
					values.length = 0
					break
				}
				values.push([guard, value])
			}
			if (values.length === requirement.length) {
				for (const [guard, value] of values) {
					url = _applyAuth(url, headers, guard, value)
				}
				applied = true
				break
			}
		}
		if (!applied) {
			throw new AuthNotReadyError(config.method + " " + config.path)
		}
	}
	const init: RequestInit = { method: config.method, headers, signal: config.options?.signal }
	if (config.cookie) {
		init.credentials = "same-origin"
	}
	const body = _encodeBody(config.body, config.bodyMode, config.bodyFields)
	if (body !== undefined) {
		init.body = body
	}
	const response = await fetch(url, init)
	return await _decodeResponse<T>(response, config.response)
}

async function _resolveAuth(provider: AuthProvider | undefined): Promise<RequestAuth | null | undefined> {
	return typeof provider === "function" ? await provider() : provider
}

function _applyAuth(url: string, headers: Record<string, string>, guard: AuthGuard, value: string): string {
	const authValue = guard.prefix ? guard.prefix + " " + value : value
	if (guard.in === "header") {
		headers[guard.param] = authValue
	} else if (guard.in === "query") {
		url = _appendQuery(url, guard.param, authValue, false)
	} else if (guard.in === "cookie") {
		document.cookie = guard.param + "=" + encodeURIComponent(authValue) + "; path=/"
	}
	return url
}

function _appendQuery(url: string, key: string, value: unknown, optional: boolean): string {
	const parts: string[] = []
	const append = (item: unknown) => {
		if (optional && (item === "" || item === 0 || item === false || item === null || item === undefined)) {
			return
		}
		parts.push(encodeURIComponent(key) + "=" + encodeURIComponent(item === null || item === undefined ? "" : String(item)))
	}
	if (Array.isArray(value)) {
		if (value.length === 0 && !optional) {
			append("")
		}
		for (const item of value) {
			append(item)
		}
	} else {
		append(value)
	}
	if (parts.length === 0) {
		return url
	}
	const sep = url.includes("?") ? "&" : "?"
	return url + sep + parts.join("&")
}

function _encodeBody(value: unknown, mode?: string, fields?: BodyField[]): BodyInit | undefined {
	if (value === undefined || value === null) {
		return undefined
	}
	if (mode === "form") {
		const form = new URLSearchParams()
		_appendFields(form, value, fields)
		return form.toString()
	}
	if (mode === "multipart") {
		const form = new FormData()
		_appendFields(form, value, fields)
		return form
	}
	return JSON.stringify(value)
}

function _appendFields(form: URLSearchParams | FormData, value: unknown, fields?: BodyField[]) {
	const data = (value || {}) as Record<string, unknown>
	const items: Array<[string, unknown]> = fields && fields.length > 0 ? fields.map((field) => [field[0], data[field[1]]]) : Object.entries(data)
	for (const [key, item] of items) {
		_appendField(form, key, item)
	}
}

function _appendField(form: URLSearchParams | FormData, key: string, item: unknown) {
	if (item === undefined || item === null) {
		return
	}
	if (Array.isArray(item)) {
		for (const child of item) {
			_appendField(form, key, child)
		}
		return
	}
	if (form instanceof FormData && typeof Blob !== "undefined" && item instanceof Blob) {
		form.append(key, item)
		return
	}
	form.append(key, String(item))
}

async function _decodeResponse<T>(response: Response, mode: string): Promise<T> {
	if (mode === "text") {
		const text = await response.text()
		if (!response.ok) {
			throw new Error(text || (response.status + " " + response.statusText))
		}
		return text as T
	}
	if (mode === "bytes") {
		const raw = await response.arrayBuffer()
		if (!response.ok) {
			throw new Error(response.status + " " + response.statusText)
		}
		return new Uint8Array(raw) as T
	}
	if (mode === "none") {
		if (!response.ok) {
			throw new Error(response.status + " " + response.statusText)
		}
		return undefined as T
	}
	const text = await response.text()
	let json: unknown = null
	if (text) {
		try {
			json = JSON.parse(text)
		} catch (e) {
			if (!response.ok) {
				throw new Error(response.status + " " + response.statusText)
			}
			throw e
		}
	}
	if (!response.ok) {
		const errorBody = json as { error?: string } | null
		throw new Error(errorBody?.error || (response.status + " " + response.statusText))
	}
	return json as T
}
`))

// WriteClientTS writes a generated TS client to w.
func (r *Router) WriteClientTS(w io.Writer) error {
	body, err := r.clientTSBody()
	if err != nil {
		return err
	}
	hash := clientgen.HashBytes(body)
	if _, err := io.WriteString(w, "// Virtuous client hash: "+hash+"\n"); err != nil {
		return err
	}
	_, err = w.Write(body)
	return err
}

// WriteClientTSFile writes a generated TS client to the file at path.
func (r *Router) WriteClientTSFile(path string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return r.WriteClientTS(f)
}

// WriteClientTSHash writes the hash of the TS client output to w.
func (r *Router) WriteClientTSHash(w io.Writer) error {
	hash, err := r.clientTSHash()
	if err != nil {
		return err
	}
	_, err = io.WriteString(w, hash)
	return err
}

// ServeClientTS writes a generated TS client as an HTTP response.
func (r *Router) ServeClientTS(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "application/typescript")
	if err := r.WriteClientTS(w); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

// ServeClientTSHash writes the hash of the TS client as an HTTP response.
func (r *Router) ServeClientTSHash(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	if err := r.WriteClientTSHash(w); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

func (r *Router) clientTSBody() ([]byte, error) {
	spec, err := buildClientSpec(r.Routes(), r.typeOverrides)
	if err != nil {
		return nil, err
	}
	return clientgen.RenderTemplate(clientTSTemplate, spec)
}

func (r *Router) clientTSHash() (string, error) {
	body, err := r.clientTSBody()
	if err != nil {
		return "", err
	}
	return clientgen.HashBytes(body), nil
}
