package httpapi

import (
	"io"
	"net/http"
	"os"
	"strings"
	"text/template"

	"github.com/swetjen/virtuous/internal/clientgen"
)

type reactQueryTSSpec struct {
	HasQueries     bool
	HasMutations   bool
	AuthParams     []clientAuthGuard
	ClientServices []clientService
	Objects        []clientObject
	Services       []reactQueryTSService
}

type reactQueryTSService struct {
	Name    string
	Methods []reactQueryTSMethod
}

type reactQueryTSMethod struct {
	ServiceName             string
	Name                    string
	HTTPMethod              string
	Path                    string
	IsQuery                 bool
	IsMutation              bool
	QueryKeyName            string
	QueryOptionsName        string
	HookName                string
	PathParams              []clientPathParam
	PathParamsType          string
	HasPathParams           bool
	QueryParams             []clientQueryParam
	QueryParamsType         string
	HasQuery                bool
	HasBody                 bool
	BodyOptional            bool
	RequestType             string
	ResponseType            string
	MutationVarsType        string
	MutationOptionsVarsType string
	MutationVarsArg         string
	MutationCallArgs        string
	QueryCallArgs           string
	QueryKeyArgs            string
	QueryKeyCallArgs        string
	QueryKeyParams          string
	QueryOptionsArgs        string
	QueryOptionsParams      string
	HookParams              string
	EnabledExpr             string
}

var reactQueryTSTemplate = template.Must(template.New("virtuous-react-query-ts").Parse(`// Code generated by Virtuous; DO NOT EDIT.

{{ if or .HasQueries .HasMutations }}
import { {{ if .HasMutations }}useMutation{{ end }}{{ if and .HasQueries .HasMutations }}, {{ end }}{{ if .HasQueries }}useQuery{{ end }}{{ if or .HasQueries .HasMutations }}, {{ end }}{{ if .HasMutations }}type UseMutationOptions{{ end }}{{ if and .HasQueries .HasMutations }}, {{ end }}{{ if .HasQueries }}type UseQueryOptions{{ end }} } from '@tanstack/react-query'
{{ end }}

export type RequestOptions = {
	auth?: string
{{- range $param := .AuthParams }}
	{{ $param.ParamName }}?: string
{{- end }}
	signal?: AbortSignal
	[key: string]: string | AbortSignal | undefined
}

export type AuthOptions = RequestOptions
{{range $object := .Objects}}
export interface {{$object.Name}} {
{{- range $field := $object.Fields}}
	{{$field.Name}}{{if $field.Optional}}?{{end}}: {{$field.Type}}{{if $field.Nullable}} | null{{end}};
{{- end}}
}
{{end}}
export function createClient(basepath: string = "/") {
	return {
{{- range $service := .ClientServices }}
		{{ $service.Name }}: {
{{- range $method := $service.Methods }}
			async {{ $method.Name }}({{ if $method.PathParams }}pathParams: { {{- range $param := $method.PathParams }}{{ $param.Name }}: {{ $param.Type }}; {{- end }} }, {{ end }}{{ if $method.HasBody }}request{{ if $method.BodyOptional }}?{{ end }}: {{ $method.RequestType }}, {{ end }}{{ if $method.HasQuery }}query?: { {{- range $param := $method.QueryParams }}{{ $param.Name }}{{ if $param.Optional }}?{{ end }}: {{ $param.Type }}; {{- end }} }, {{ end }}options?: RequestOptions): Promise<{{ if eq $method.ResponseMode "none" }}void{{ else if $method.ResponseType }}{{ $method.ResponseType }}{{ else }}unknown{{ end }}> {
				const headers: Record<string, string> = {
					"Accept": "{{ $method.AcceptType }}",
{{- if $method.HasBody }}
{{- if ne $method.BodyMode "multipart" }}
					"Content-Type": "{{ $method.RequestMedia }}",
{{- end }}
{{- end }}
				}
				let url = basepath + "{{ $method.Path }}"
{{- if $method.PathParams }}
				if (!pathParams) {
					throw new Error("pathParams is required")
				}
{{- range $param := $method.PathParams }}
				url = url.replace("{{ printf "{%s}" $param.Name }}", encodeURIComponent(String(pathParams.{{ $param.Name }})))
{{- end }}
{{- end }}
{{- if $method.HasQuery }}
				const queryParts: string[] = []
				const appendQuery = (key: string, value: unknown, optional: boolean) => {
					if (value === undefined || value === null) {
						if (optional) {
							return
						}
						queryParts.push(encodeURIComponent(key) + "=")
						return
					}
					if (Array.isArray(value)) {
						if (value.length === 0) {
							if (!optional) {
								queryParts.push(encodeURIComponent(key) + "=")
							}
							return
						}
						for (const item of value) {
							if (optional && (item === "" || item === 0 || item === false || item === null || item === undefined)) {
								continue
							}
							const encoded = item === null || item === undefined ? "" : String(item)
							queryParts.push(encodeURIComponent(key) + "=" + encodeURIComponent(encoded))
						}
						return
					}
					if (optional && (value === "" || value === 0 || value === false)) {
						return
					}
					queryParts.push(encodeURIComponent(key) + "=" + encodeURIComponent(String(value)))
				}
{{- range $param := $method.QueryParams }}
				appendQuery("{{ $param.Name }}", query && query.{{ $param.Name }}, {{ if $param.Optional }}true{{ else }}false{{ end }})
{{- end }}
				if (queryParts.length > 0) {
					const sep = url.includes("?") ? "&" : "?"
					url = url + sep + queryParts.join("&")
				}
{{- end }}
{{- if $method.HasAuth }}
				const applyAuth = (location: string, param: string, prefix: string, value: string) => {
					const authValue = prefix ? prefix + " " + value : value
					if (location === "header") {
						headers[param] = authValue
					} else if (location === "query") {
						const sep = url.includes("?") ? "&" : "?"
						url = url + sep + encodeURIComponent(param) + "=" + encodeURIComponent(authValue)
					} else if (location === "cookie") {
						document.cookie = param + "=" + encodeURIComponent(authValue) + "; path=/"
					}
				}
				let authApplied = false
{{- range $req := $method.AuthReqs }}
				if (!authApplied) {
{{- if eq (len $req.Guards) 1 }}
{{- range $guard := $req.Guards }}
					const {{ $guard.ParamName }}Value = options && (options.{{ $guard.ParamName }} || options.auth)
					if ({{ $guard.ParamName }}Value) {
						applyAuth("{{ $guard.Spec.In }}", "{{ $guard.Spec.Param }}", "{{ $guard.Spec.Prefix }}", {{ $guard.ParamName }}Value)
						authApplied = true
					}
{{- end }}
{{- else }}
					const hasAuthValues = true{{ range $guard := $req.Guards }} && !!(options && options.{{ $guard.ParamName }}){{ end }}
					if (hasAuthValues) {
{{- range $guard := $req.Guards }}
						applyAuth("{{ $guard.Spec.In }}", "{{ $guard.Spec.Param }}", "{{ $guard.Spec.Prefix }}", options!.{{ $guard.ParamName }}!)
{{- end }}
						authApplied = true
					}
{{- end }}
				}
{{- end }}
{{- end }}
{{- if and $method.HasBody (eq $method.BodyMode "form") }}
				const encodeForm = (value: unknown): string => {
					const form = new URLSearchParams()
					const appendForm = (key: string, item: unknown) => {
						if (item === undefined || item === null) {
							return
						}
						if (Array.isArray(item)) {
							for (const child of item) {
								if (child !== undefined && child !== null) {
									form.append(key, String(child))
								}
							}
							return
						}
						form.append(key, String(item))
					}
					const data = (value || {}) as Record<string, unknown>
{{- if $method.BodyFields }}
{{- range $field := $method.BodyFields }}
					appendForm("{{ $field.WireName }}", data.{{ $field.Name }})
{{- end }}
{{- else }}
					for (const [key, item] of Object.entries(data)) {
						appendForm(key, item)
					}
{{- end }}
					return form.toString()
				}
{{- end }}
{{- if and $method.HasBody (eq $method.BodyMode "multipart") }}
				const encodeMultipart = (value: unknown): FormData => {
					const form = new FormData()
					const appendMultipart = (key: string, item: unknown) => {
						if (item === undefined || item === null) {
							return
						}
						if (Array.isArray(item)) {
							for (const child of item) {
								appendMultipart(key, child)
							}
							return
						}
						if (typeof Blob !== "undefined" && item instanceof Blob) {
							form.append(key, item)
							return
						}
						form.append(key, String(item))
					}
					const data = (value || {}) as Record<string, unknown>
{{- if $method.BodyFields }}
{{- range $field := $method.BodyFields }}
					appendMultipart("{{ $field.WireName }}", data.{{ $field.Name }})
{{- end }}
{{- else }}
					for (const [key, item] of Object.entries(data)) {
						appendMultipart(key, item)
					}
{{- end }}
					return form
				}
{{- end }}
				const response = await fetch(url, {
					method: "{{ $method.HTTPMethod }}",
					headers,
{{- if $method.HasCookieAuth }}
					credentials: "same-origin",
{{- end }}
					signal: options?.signal,
{{- if $method.HasBody }}
{{- if $method.BodyOptional }}
					body: request === undefined || request === null ? undefined : {{ if eq $method.BodyMode "form" }}encodeForm(request){{ else if eq $method.BodyMode "multipart" }}encodeMultipart(request){{ else }}JSON.stringify(request){{ end }},
{{- else }}
					body: {{ if eq $method.BodyMode "form" }}encodeForm(request || {}){{ else if eq $method.BodyMode "multipart" }}encodeMultipart(request || {}){{ else }}JSON.stringify(request || {}){{ end }},
{{- end }}
{{- end }}
				})
{{- if eq $method.ResponseMode "json" }}
				const text = await response.text()
				let json: {{ if $method.ResponseType }}{{ $method.ResponseType }}{{ else }}Record<string, unknown>{{ end }} | null = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new Error(response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					const errorBody = json as { error?: string } | null
					if (errorBody && errorBody.error) {
						throw new Error(errorBody.error)
					}
					throw new Error(response.status + " " + response.statusText)
				}
				return json as {{ if $method.ResponseType }}{{ $method.ResponseType }}{{ else }}unknown{{ end }}
{{- else if eq $method.ResponseMode "text" }}
				const text = await response.text()
				if (!response.ok) {
					throw new Error(text || (response.status + " " + response.statusText))
				}
				return text as {{ if $method.ResponseType }}{{ $method.ResponseType }}{{ else }}string{{ end }}
{{- else if eq $method.ResponseMode "bytes" }}
				const raw = await response.arrayBuffer()
				if (!response.ok) {
					throw new Error(response.status + " " + response.statusText)
				}
				return new Uint8Array(raw) as {{ if $method.ResponseType }}{{ $method.ResponseType }}{{ else }}Uint8Array{{ end }}
{{- else }}
				if (!response.ok) {
					throw new Error(response.status + " " + response.statusText)
				}
				return
{{- end }}
			},
{{- end }}
		},
{{- end }}
	}
}

export const reactQueryClient = createClient('')
{{ range $service := .Services }}{{ range $method := $service.Methods }}
{{- if $method.IsQuery }}
export function {{ $method.QueryKeyName }}({{ $method.QueryKeyParams }}) {
	return [{{ $method.QueryKeyArgs }}] as const
}

export function {{ $method.QueryOptionsName }}({{ $method.QueryOptionsParams }}) {
	return {
		queryKey: {{ $method.QueryKeyName }}({{ $method.QueryKeyCallArgs }}),
		queryFn: ({ signal }: { signal?: AbortSignal }) => reactQueryClient.{{ $method.ServiceName }}.{{ $method.Name }}({{ $method.QueryCallArgs }}),
{{- if $method.EnabledExpr }}
		enabled: {{ $method.EnabledExpr }},
{{- end }}
	}
}

export function {{ $method.HookName }}({{ $method.HookParams }}) {
	return useQuery({
		...{{ $method.QueryOptionsName }}({{ $method.QueryOptionsArgs }}),
		...queryOptions,
	})
}
{{- else }}
export function {{ $method.HookName }}({{ $method.HookParams }}) {
	return useMutation({
		mutationFn: {{ if $method.MutationVarsArg }}({{ $method.MutationVarsArg }}){{ else }}(){{ end }} => reactQueryClient.{{ $method.ServiceName }}.{{ $method.Name }}({{ $method.MutationCallArgs }}),
		...mutationOptions,
	})
}
{{- end }}
{{ end }}{{ end }}`))

// WriteReactQueryTS writes a generated TanStack React Query companion client to w.
func (r *Router) WriteReactQueryTS(w io.Writer) error {
	body, err := r.reactQueryTSBody()
	if err != nil {
		return err
	}
	hash := clientgen.HashBytes(body)
	if _, err := io.WriteString(w, "// Virtuous React Query client hash: "+hash+"\n"); err != nil {
		return err
	}
	_, err = w.Write(body)
	return err
}

// WriteReactQueryTSFile writes a generated TanStack React Query companion client to the file at path.
func (r *Router) WriteReactQueryTSFile(path string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return r.WriteReactQueryTS(f)
}

// WriteReactQueryTSHash writes the hash of the React Query TS client output to w.
func (r *Router) WriteReactQueryTSHash(w io.Writer) error {
	hash, err := r.reactQueryTSHash()
	if err != nil {
		return err
	}
	_, err = io.WriteString(w, hash)
	return err
}

// ServeReactQueryTS writes a generated TanStack React Query companion client as an HTTP response.
func (r *Router) ServeReactQueryTS(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "application/typescript")
	if err := r.WriteReactQueryTS(w); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

// ServeReactQueryTSHash writes the hash of the React Query TS client as an HTTP response.
func (r *Router) ServeReactQueryTSHash(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	if err := r.WriteReactQueryTSHash(w); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

func (r *Router) reactQueryTSBody() ([]byte, error) {
	clientSpec, err := buildClientSpec(r.Routes(), r.typeOverrides)
	if err != nil {
		return nil, err
	}
	spec := buildReactQueryTSSpec(clientSpec)
	return clientgen.RenderTemplate(reactQueryTSTemplate, spec)
}

func (r *Router) reactQueryTSHash() (string, error) {
	body, err := r.reactQueryTSBody()
	if err != nil {
		return "", err
	}
	return clientgen.HashBytes(body), nil
}

func buildReactQueryTSSpec(spec clientSpec) reactQueryTSSpec {
	out := reactQueryTSSpec{
		AuthParams:     reactQueryAuthParams(spec),
		ClientServices: spec.Services,
		Objects:        spec.Objects,
	}
	nameCounts := reactQueryMethodNameCounts(spec)
	for _, service := range spec.Services {
		rqService := reactQueryTSService{Name: service.Name}
		for _, method := range service.Methods {
			rqMethod := buildReactQueryTSMethod(service.Name, method, nameCounts[method.Name] > 1)
			if rqMethod.IsQuery {
				out.HasQueries = true
			}
			if rqMethod.IsMutation {
				out.HasMutations = true
			}
			rqService.Methods = append(rqService.Methods, rqMethod)
		}
		out.Services = append(out.Services, rqService)
	}
	return out
}

func reactQueryAuthParams(spec clientSpec) []clientAuthGuard {
	seen := map[string]struct{}{"auth": {}}
	var out []clientAuthGuard
	for _, service := range spec.Services {
		for _, method := range service.Methods {
			for _, param := range method.AuthParams {
				if _, ok := seen[param.ParamName]; ok {
					continue
				}
				seen[param.ParamName] = struct{}{}
				out = append(out, param)
			}
		}
	}
	return out
}

func buildReactQueryTSMethod(serviceName string, method clientMethod, nameCollides bool) reactQueryTSMethod {
	exportBase := method.Name
	if nameCollides {
		exportBase = camelizeDown(serviceName + "_" + method.Name)
	}
	exportName := upperFirst(exportBase)
	rqMethod := reactQueryTSMethod{
		ServiceName:      serviceName,
		Name:             method.Name,
		HTTPMethod:       method.HTTPMethod,
		Path:             method.Path,
		IsQuery:          isReactQueryQueryMethod(method.HTTPMethod),
		IsMutation:       !isReactQueryQueryMethod(method.HTTPMethod),
		QueryKeyName:     exportBase + "QueryKey",
		QueryOptionsName: exportBase + "QueryOptions",
		HookName:         "use" + exportName,
		PathParams:       method.PathParams,
		PathParamsType:   reactQueryPathParamsType(method.PathParams),
		HasPathParams:    len(method.PathParams) > 0,
		QueryParams:      method.QueryParams,
		QueryParamsType:  reactQueryQueryParamsType(method.QueryParams),
		HasQuery:         method.HasQuery,
		HasBody:          method.HasBody,
		BodyOptional:     method.BodyOptional,
		RequestType:      reactQueryRequestType(method.RequestType),
		ResponseType:     reactQueryResponseType(method),
	}
	if rqMethod.IsQuery {
		fillReactQueryQueryArgs(&rqMethod)
	} else {
		fillReactQueryMutationArgs(&rqMethod)
	}
	return rqMethod
}

func reactQueryMethodNameCounts(spec clientSpec) map[string]int {
	counts := map[string]int{}
	for _, service := range spec.Services {
		for _, method := range service.Methods {
			counts[method.Name]++
		}
	}
	return counts
}

func fillReactQueryQueryArgs(method *reactQueryTSMethod) {
	var keyParams []string
	var keyArgs []string
	var optionsParams []string
	var optionsArgs []string
	var hookParams []string
	var rawCallArgs []string

	if method.HasPathParams {
		keyParams = append(keyParams, "pathParams?: "+method.PathParamsType)
		keyArgs = append(keyArgs, "pathParams")
		optionsParams = append(optionsParams, "pathParams: "+method.PathParamsType+" | undefined")
		optionsArgs = append(optionsArgs, "pathParams")
		hookParams = append(hookParams, "pathParams: "+method.PathParamsType+" | undefined")
		rawCallArgs = append(rawCallArgs, "pathParams!")
		method.EnabledExpr = reactQueryEnabledExpr(method.PathParams)
	}
	if method.HasBody {
		optional := ""
		if method.BodyOptional {
			optional = "?"
		}
		keyParams = append(keyParams, "request"+optional+": "+method.RequestType)
		keyArgs = append(keyArgs, "request")
		optionsParams = append(optionsParams, "request"+optional+": "+method.RequestType)
		optionsArgs = append(optionsArgs, "request")
		hookParams = append(hookParams, "request"+optional+": "+method.RequestType)
		rawCallArgs = append(rawCallArgs, "request")
	}
	if method.HasQuery {
		keyParams = append(keyParams, "query?: "+method.QueryParamsType)
		keyArgs = append(keyArgs, "query")
		optionsParams = append(optionsParams, "query?: "+method.QueryParamsType)
		optionsArgs = append(optionsArgs, "query")
		hookParams = append(hookParams, "query?: "+method.QueryParamsType)
		rawCallArgs = append(rawCallArgs, "query")
	}
	optionsParams = append(optionsParams, "requestOptions?: RequestOptions")
	optionsArgs = append(optionsArgs, "requestOptions")
	hookParams = append(hookParams, "requestOptions?: RequestOptions")
	hookParams = append(hookParams, "queryOptions?: Omit<UseQueryOptions<"+method.ResponseType+", Error>, 'queryKey' | 'queryFn'>")
	rawCallArgs = append(rawCallArgs, "{ ...requestOptions, signal: signal ?? requestOptions?.signal }")

	method.QueryKeyParams = strings.Join(keyParams, ", ")
	method.QueryKeyArgs = reactQueryKeyArgs(method, keyArgs)
	method.QueryKeyCallArgs = strings.Join(keyArgs, ", ")
	method.QueryOptionsParams = strings.Join(optionsParams, ", ")
	method.QueryOptionsArgs = strings.Join(optionsArgs, ", ")
	method.HookParams = strings.Join(hookParams, ", ")
	method.QueryCallArgs = strings.Join(rawCallArgs, ", ")
}

func fillReactQueryMutationArgs(method *reactQueryTSMethod) {
	fields := reactQueryMutationVarFields(method)
	if len(fields) > 0 {
		method.MutationVarsType = "{ " + strings.Join(fields, "; ") + " }"
		method.MutationOptionsVarsType = method.MutationVarsType
		method.MutationVarsArg = "variables: " + method.MutationVarsType
		if method.optionalBodyOnlyMutation() {
			method.MutationOptionsVarsType = method.MutationVarsType + " | void"
			method.MutationVarsArg = "variables?: " + method.MutationVarsType
		}
	}

	method.HookParams = "requestOptions?: RequestOptions, mutationOptions?: UseMutationOptions<" + method.ResponseType + ", Error, "
	if method.MutationOptionsVarsType == "" {
		method.HookParams += "void"
	} else {
		method.HookParams += method.MutationOptionsVarsType
	}
	method.HookParams += ">"

	callArgs := make([]string, 0, 4)
	if method.HasPathParams {
		callArgs = append(callArgs, "variables.pathParams")
	}
	if method.HasBody {
		if method.optionalBodyOnlyMutation() {
			callArgs = append(callArgs, "variables?.request")
		} else {
			callArgs = append(callArgs, "variables.request")
		}
	}
	if method.HasQuery {
		callArgs = append(callArgs, "variables.query")
	}
	callArgs = append(callArgs, "requestOptions")
	method.MutationCallArgs = strings.Join(callArgs, ", ")
}

func (method reactQueryTSMethod) optionalBodyOnlyMutation() bool {
	return method.HasBody && method.BodyOptional && !method.HasPathParams && !method.HasQuery
}

func reactQueryMutationVarFields(method *reactQueryTSMethod) []string {
	var fields []string
	if method.HasPathParams {
		fields = append(fields, "pathParams: "+method.PathParamsType)
	}
	if method.HasBody {
		optional := ""
		if method.BodyOptional {
			optional = "?"
		}
		fields = append(fields, "request"+optional+": "+method.RequestType)
	}
	if method.HasQuery {
		fields = append(fields, "query?: "+method.QueryParamsType)
	}
	return fields
}

func reactQueryKeyArgs(method *reactQueryTSMethod, args []string) string {
	parts := []string{quoteTSString(method.HTTPMethod + " " + method.Path)}
	parts = append(parts, args...)
	return strings.Join(parts, ", ")
}

func reactQueryPathParamsType(params []clientPathParam) string {
	if len(params) == 0 {
		return ""
	}
	fields := make([]string, 0, len(params))
	for _, param := range params {
		fields = append(fields, param.Name+": "+param.Type)
	}
	return "{ " + strings.Join(fields, "; ") + " }"
}

func reactQueryQueryParamsType(params []clientQueryParam) string {
	if len(params) == 0 {
		return ""
	}
	fields := make([]string, 0, len(params))
	for _, param := range params {
		optional := ""
		if param.Optional {
			optional = "?"
		}
		fields = append(fields, param.Name+optional+": "+param.Type)
	}
	return "{ " + strings.Join(fields, "; ") + " }"
}

func reactQueryEnabledExpr(params []clientPathParam) string {
	if len(params) == 0 {
		return ""
	}
	checks := make([]string, 0, len(params))
	for _, param := range params {
		checks = append(checks, "pathParams."+param.Name+" !== undefined && pathParams."+param.Name+" !== null")
	}
	return "!!pathParams && " + strings.Join(checks, " && ")
}

func reactQueryRequestType(requestType string) string {
	if requestType == "" {
		return "any"
	}
	return requestType
}

func reactQueryResponseType(method clientMethod) string {
	if method.ResponseMode == "none" {
		return "void"
	}
	if method.ResponseType != "" {
		return method.ResponseType
	}
	return "unknown"
}

func isReactQueryQueryMethod(method string) bool {
	method = strings.ToUpper(method)
	return method == "GET" || method == "HEAD"
}

func upperFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func quoteTSString(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "\\'") + "'"
}
